// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gtsrb_cnn_maxpool2x2_valid_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_in_address0,
        feature_in_ce0,
        feature_in_q0,
        feature_in_address1,
        feature_in_ce1,
        feature_in_q1,
        feature_out_address1,
        feature_out_ce1,
        feature_out_we1,
        feature_out_d1,
        grp_fu_582_p_din0,
        grp_fu_582_p_din1,
        grp_fu_582_p_opcode,
        grp_fu_582_p_dout0,
        grp_fu_582_p_ce,
        grp_fu_586_p_din0,
        grp_fu_586_p_din1,
        grp_fu_586_p_opcode,
        grp_fu_586_p_dout0,
        grp_fu_586_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] feature_in_address0;
output   feature_in_ce0;
input  [31:0] feature_in_q0;
output  [13:0] feature_in_address1;
output   feature_in_ce1;
input  [31:0] feature_in_q1;
output  [11:0] feature_out_address1;
output   feature_out_ce1;
output   feature_out_we1;
output  [31:0] feature_out_d1;
output  [31:0] grp_fu_582_p_din0;
output  [31:0] grp_fu_582_p_din1;
output  [4:0] grp_fu_582_p_opcode;
input  [0:0] grp_fu_582_p_dout0;
output   grp_fu_582_p_ce;
output  [31:0] grp_fu_586_p_din0;
output  [31:0] grp_fu_586_p_din1;
output  [4:0] grp_fu_586_p_opcode;
input  [0:0] grp_fu_586_p_dout0;
output   grp_fu_586_p_ce;

reg ap_idle;
reg[13:0] feature_in_address0;
reg feature_in_ce0;
reg[13:0] feature_in_address1;
reg feature_in_ce1;
reg feature_out_ce1;
reg feature_out_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln48_fu_290_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_187;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln48_reg_1058;
wire    ap_block_pp0_stage1_11001;
wire   [4:0] c_cast5_mid2_v_fu_331_p3;
reg   [4:0] c_cast5_mid2_v_reg_1062;
reg   [4:0] c_cast5_mid2_v_reg_1062_pp0_iter1_reg;
reg   [8:0] tmp_1_reg_1078;
reg   [8:0] tmp_1_reg_1078_pp0_iter1_reg;
wire   [13:0] add_ln62_fu_613_p2;
reg   [13:0] add_ln62_reg_1083;
reg   [13:0] add_ln62_reg_1083_pp0_iter1_reg;
reg   [13:0] add_ln62_reg_1083_pp0_iter2_reg;
wire   [7:0] add_ln67_fu_619_p2;
reg   [7:0] add_ln67_reg_1088;
reg   [7:0] add_ln67_reg_1088_pp0_iter1_reg;
reg   [31:0] v1_reg_1093;
wire   [31:0] m_1_fu_712_p3;
reg   [31:0] m_1_reg_1100;
wire   [31:0] m_3_fu_817_p3;
reg   [31:0] m_3_reg_1112;
wire   [11:0] add_ln67_1_fu_830_p2;
reg   [11:0] add_ln67_1_reg_1119;
reg   [11:0] add_ln67_1_reg_1119_pp0_iter3_reg;
reg   [11:0] add_ln67_1_reg_1119_pp0_iter4_reg;
wire   [31:0] m_5_fu_923_p3;
reg   [31:0] m_5_reg_1129;
reg   [31:0] m_5_reg_1129_pp0_iter4_reg;
reg   [31:0] v3_reg_1136;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln59_fu_587_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln60_fu_598_p1;
wire   [63:0] zext_ln61_fu_730_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln62_fu_836_p1;
wire   [63:0] zext_ln67_fu_1019_p1;
reg   [3:0] w_fu_98;
wire   [3:0] add_ln50_fu_625_p2;
wire    ap_loop_init;
reg   [3:0] h_fu_102;
wire   [3:0] select_ln49_fu_495_p3;
reg   [7:0] indvar_flatten_fu_106;
wire   [7:0] select_ln49_1_fu_637_p3;
reg   [4:0] c_fu_110;
reg   [11:0] indvar_flatten41_fu_114;
wire   [11:0] add_ln48_fu_296_p2;
reg   [31:0] grp_fu_176_p0;
reg   [31:0] grp_fu_176_p1;
reg   [31:0] grp_fu_182_p0;
reg   [31:0] grp_fu_182_p1;
wire   [5:0] p_shl3_fu_232_p3;
wire   [8:0] p_shl2_fu_224_p3;
wire   [8:0] p_shl3_cast_fu_240_p1;
wire   [8:0] sub_ln55_fu_244_p2;
wire   [4:0] p_shl1_fu_266_p3;
wire   [7:0] p_shl_fu_258_p3;
wire   [7:0] p_shl1_cast_fu_274_p1;
wire   [9:0] shl_ln_fu_250_p3;
wire   [0:0] icmp_ln49_fu_311_p2;
wire   [4:0] add_ln48_1_fu_325_p2;
wire   [7:0] sub_ln67_fu_278_p2;
wire   [9:0] add_ln57_fu_284_p2;
wire   [0:0] icmp_ln50_fu_373_p2;
wire   [0:0] not_exitcond_flatten_fu_367_p2;
wire   [3:0] h_mid27_fu_317_p3;
wire   [0:0] icmp_ln50_mid240_fu_379_p2;
wire   [0:0] empty_45_fu_391_p2;
wire   [3:0] add_ln49_fu_385_p2;
wire   [5:0] p_shl3_mid1_fu_413_p3;
wire   [8:0] p_shl2_mid1_fu_405_p3;
wire   [8:0] p_shl3_cast_mid1_fu_421_p1;
wire   [8:0] sub_ln55_1_fu_425_p2;
wire   [9:0] shl_ln55_mid1_fu_431_p3;
wire   [9:0] shl_ln55_mid228_fu_343_p3;
wire   [4:0] p_shl1_mid1_fu_455_p3;
wire   [7:0] p_shl_mid1_fu_447_p3;
wire   [7:0] p_shl1_cast_mid1_fu_463_p1;
wire   [7:0] sub_ln67_1_fu_467_p2;
wire   [7:0] sub_ln67_mid236_fu_351_p3;
wire   [9:0] add_ln57_2_fu_481_p2;
wire   [9:0] add_ln57_mid238_fu_359_p3;
wire   [3:0] w_mid2_fu_397_p3;
wire   [4:0] shl_ln55_1_fu_507_p3;
wire   [9:0] zext_ln55_1_fu_515_p1;
wire   [9:0] shl_ln55_mid2_fu_439_p3;
wire   [4:0] or_ln56_fu_525_p2;
wire   [9:0] zext_ln56_fu_531_p1;
wire   [9:0] add_ln56_fu_535_p2;
wire   [9:0] add_ln57_mid2_fu_487_p3;
wire   [9:0] add_ln58_fu_555_p2;
wire   [9:0] add_ln55_fu_519_p2;
wire   [8:0] tmp_fu_569_p4;
wire   [13:0] add_ln_fu_579_p3;
wire   [13:0] shl_ln1_fu_541_p3;
wire   [13:0] c_cast_mid2_fu_339_p1;
wire   [13:0] add_ln60_fu_592_p2;
wire   [9:0] add_ln57_1_fu_549_p2;
wire   [13:0] shl_ln2_fu_561_p3;
wire   [7:0] zext_ln55_fu_503_p1;
wire   [7:0] sub_ln67_mid2_fu_473_p3;
wire   [7:0] add_ln49_1_fu_631_p2;
wire   [31:0] bitcast_ln63_fu_670_p1;
wire   [7:0] tmp_2_fu_674_p4;
wire   [22:0] trunc_ln63_fu_684_p1;
wire   [0:0] icmp_ln63_1_fu_694_p2;
wire   [0:0] icmp_ln63_fu_688_p2;
wire   [0:0] or_ln63_fu_700_p2;
wire   [0:0] and_ln63_fu_706_p2;
wire   [13:0] add_ln1_fu_724_p3;
wire   [31:0] bitcast_ln64_fu_735_p1;
wire   [31:0] bitcast_ln64_1_fu_752_p1;
wire   [7:0] tmp_4_fu_738_p4;
wire   [22:0] trunc_ln64_fu_748_p1;
wire   [0:0] icmp_ln64_1_fu_775_p2;
wire   [0:0] icmp_ln64_fu_769_p2;
wire   [7:0] tmp_5_fu_755_p4;
wire   [22:0] trunc_ln64_1_fu_765_p1;
wire   [0:0] icmp_ln64_3_fu_793_p2;
wire   [0:0] icmp_ln64_2_fu_787_p2;
wire   [0:0] or_ln64_fu_781_p2;
wire   [0:0] or_ln64_1_fu_799_p2;
wire   [0:0] and_ln64_fu_805_p2;
wire   [0:0] and_ln64_1_fu_811_p2;
wire   [11:0] shl_ln3_fu_823_p3;
wire   [11:0] c_cast5_mid2_fu_721_p1;
wire   [31:0] bitcast_ln65_fu_840_p1;
wire   [31:0] bitcast_ln65_1_fu_858_p1;
wire   [7:0] tmp_7_fu_844_p4;
wire   [22:0] trunc_ln65_fu_854_p1;
wire   [0:0] icmp_ln65_1_fu_881_p2;
wire   [0:0] icmp_ln65_fu_875_p2;
wire   [7:0] tmp_8_fu_861_p4;
wire   [22:0] trunc_ln65_1_fu_871_p1;
wire   [0:0] icmp_ln65_3_fu_899_p2;
wire   [0:0] icmp_ln65_2_fu_893_p2;
wire   [0:0] or_ln65_fu_887_p2;
wire   [0:0] or_ln65_1_fu_905_p2;
wire   [0:0] and_ln65_fu_911_p2;
wire   [0:0] and_ln65_1_fu_917_p2;
wire   [31:0] bitcast_ln66_fu_930_p1;
wire   [31:0] bitcast_ln66_1_fu_947_p1;
wire   [7:0] tmp_s_fu_933_p4;
wire   [22:0] trunc_ln66_fu_943_p1;
wire   [0:0] icmp_ln66_1_fu_970_p2;
wire   [0:0] icmp_ln66_fu_964_p2;
wire   [7:0] tmp_10_fu_950_p4;
wire   [22:0] trunc_ln66_1_fu_960_p1;
wire   [0:0] icmp_ln66_3_fu_988_p2;
wire   [0:0] icmp_ln66_2_fu_982_p2;
wire   [0:0] or_ln66_fu_976_p2;
wire   [0:0] or_ln66_1_fu_994_p2;
wire   [0:0] and_ln66_fu_1000_p2;
wire   [0:0] and_ln66_1_fu_1006_p2;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

gtsrb_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        c_fu_110 <= 5'd0;
    end else if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_fu_110 <= c_cast5_mid2_v_fu_331_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        h_fu_102 <= 4'd0;
    end else if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_fu_102 <= select_ln49_fu_495_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        indvar_flatten41_fu_114 <= 12'd0;
    end else if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten41_fu_114 <= add_ln48_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        indvar_flatten_fu_106 <= 8'd0;
    end else if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten_fu_106 <= select_ln49_1_fu_637_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        w_fu_98 <= 4'd0;
    end else if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w_fu_98 <= add_ln50_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln62_reg_1083 <= add_ln62_fu_613_p2;
        add_ln67_reg_1088 <= add_ln67_fu_619_p2;
        c_cast5_mid2_v_reg_1062 <= c_cast5_mid2_v_fu_331_p3;
        tmp_1_reg_1078 <= {{add_ln57_1_fu_549_p2[9:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln62_reg_1083_pp0_iter1_reg <= add_ln62_reg_1083;
        add_ln62_reg_1083_pp0_iter2_reg <= add_ln62_reg_1083_pp0_iter1_reg;
        add_ln67_reg_1088_pp0_iter1_reg <= add_ln67_reg_1088;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        c_cast5_mid2_v_reg_1062_pp0_iter1_reg <= c_cast5_mid2_v_reg_1062;
        icmp_ln48_reg_1058 <= icmp_ln48_fu_290_p2;
        m_1_reg_1100 <= m_1_fu_712_p3;
        tmp_1_reg_1078_pp0_iter1_reg <= tmp_1_reg_1078;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln67_1_reg_1119 <= add_ln67_1_fu_830_p2;
        add_ln67_1_reg_1119_pp0_iter3_reg <= add_ln67_1_reg_1119;
        add_ln67_1_reg_1119_pp0_iter4_reg <= add_ln67_1_reg_1119_pp0_iter3_reg;
        m_3_reg_1112 <= m_3_fu_817_p3;
        m_5_reg_1129 <= m_5_fu_923_p3;
        m_5_reg_1129_pp0_iter4_reg <= m_5_reg_1129;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln48_reg_1058 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_187 <= feature_in_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_reg_1058 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v1_reg_1093 <= feature_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        v3_reg_1136 <= feature_in_q0;
    end
end

always @ (*) begin
    if (((icmp_ln48_fu_290_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_in_address0 = zext_ln62_fu_836_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_in_address0 = zext_ln60_fu_598_p1;
    end else begin
        feature_in_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_in_address1 = zext_ln61_fu_730_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_in_address1 = zext_ln59_fu_587_p1;
    end else begin
        feature_in_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feature_in_ce0 = 1'b1;
    end else begin
        feature_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feature_in_ce1 = 1'b1;
    end else begin
        feature_in_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_out_ce1 = 1'b1;
    end else begin
        feature_out_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_out_we1 = 1'b1;
    end else begin
        feature_out_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_176_p0 = v1_reg_1093;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_176_p0 = feature_in_q1;
        end else begin
            grp_fu_176_p0 = 'bx;
        end
    end else begin
        grp_fu_176_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_176_p1 = m_1_fu_712_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_176_p1 = 32'd4286564766;
        end else begin
            grp_fu_176_p1 = 'bx;
        end
    end else begin
        grp_fu_176_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_182_p0 = v3_reg_1136;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_182_p0 = feature_in_q1;
    end else begin
        grp_fu_182_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_182_p1 = m_5_reg_1129;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_182_p1 = m_3_reg_1112;
    end else begin
        grp_fu_182_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1_fu_724_p3 = {{tmp_1_reg_1078_pp0_iter1_reg}, {c_cast5_mid2_v_reg_1062_pp0_iter1_reg}};

assign add_ln48_1_fu_325_p2 = (c_fu_110 + 5'd1);

assign add_ln48_fu_296_p2 = (indvar_flatten41_fu_114 + 12'd1);

assign add_ln49_1_fu_631_p2 = (indvar_flatten_fu_106 + 8'd1);

assign add_ln49_fu_385_p2 = (h_mid27_fu_317_p3 + 4'd1);

assign add_ln50_fu_625_p2 = (w_mid2_fu_397_p3 + 4'd1);

assign add_ln55_fu_519_p2 = (zext_ln55_1_fu_515_p1 + shl_ln55_mid2_fu_439_p3);

assign add_ln56_fu_535_p2 = (zext_ln56_fu_531_p1 + shl_ln55_mid2_fu_439_p3);

assign add_ln57_1_fu_549_p2 = (zext_ln55_1_fu_515_p1 + add_ln57_mid2_fu_487_p3);

assign add_ln57_2_fu_481_p2 = (shl_ln55_mid1_fu_431_p3 + 10'd28);

assign add_ln57_fu_284_p2 = (shl_ln_fu_250_p3 + 10'd28);

assign add_ln57_mid238_fu_359_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? 10'd28 : add_ln57_fu_284_p2);

assign add_ln57_mid2_fu_487_p3 = ((icmp_ln50_mid240_fu_379_p2[0:0] == 1'b1) ? add_ln57_2_fu_481_p2 : add_ln57_mid238_fu_359_p3);

assign add_ln58_fu_555_p2 = (zext_ln56_fu_531_p1 + add_ln57_mid2_fu_487_p3);

assign add_ln60_fu_592_p2 = (shl_ln1_fu_541_p3 + c_cast_mid2_fu_339_p1);

assign add_ln62_fu_613_p2 = (shl_ln2_fu_561_p3 + c_cast_mid2_fu_339_p1);

assign add_ln67_1_fu_830_p2 = (shl_ln3_fu_823_p3 + c_cast5_mid2_fu_721_p1);

assign add_ln67_fu_619_p2 = (zext_ln55_fu_503_p1 + sub_ln67_mid2_fu_473_p3);

assign add_ln_fu_579_p3 = {{tmp_fu_569_p4}, {c_cast5_mid2_v_fu_331_p3}};

assign and_ln63_fu_706_p2 = (or_ln63_fu_700_p2 & grp_fu_582_p_dout0);

assign and_ln64_1_fu_811_p2 = (grp_fu_582_p_dout0 & and_ln64_fu_805_p2);

assign and_ln64_fu_805_p2 = (or_ln64_fu_781_p2 & or_ln64_1_fu_799_p2);

assign and_ln65_1_fu_917_p2 = (grp_fu_586_p_dout0 & and_ln65_fu_911_p2);

assign and_ln65_fu_911_p2 = (or_ln65_fu_887_p2 & or_ln65_1_fu_905_p2);

assign and_ln66_1_fu_1006_p2 = (grp_fu_586_p_dout0 & and_ln66_fu_1000_p2);

assign and_ln66_fu_1000_p2 = (or_ln66_fu_976_p2 & or_ln66_1_fu_994_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bitcast_ln63_fu_670_p1 = reg_187;

assign bitcast_ln64_1_fu_752_p1 = m_1_reg_1100;

assign bitcast_ln64_fu_735_p1 = v1_reg_1093;

assign bitcast_ln65_1_fu_858_p1 = m_3_reg_1112;

assign bitcast_ln65_fu_840_p1 = reg_187;

assign bitcast_ln66_1_fu_947_p1 = m_5_reg_1129_pp0_iter4_reg;

assign bitcast_ln66_fu_930_p1 = v3_reg_1136;

assign c_cast5_mid2_fu_721_p1 = c_cast5_mid2_v_reg_1062_pp0_iter1_reg;

assign c_cast5_mid2_v_fu_331_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? add_ln48_1_fu_325_p2 : c_fu_110);

assign c_cast_mid2_fu_339_p1 = c_cast5_mid2_v_fu_331_p3;

assign empty_45_fu_391_p2 = (icmp_ln50_mid240_fu_379_p2 | icmp_ln49_fu_311_p2);

assign feature_out_address1 = zext_ln67_fu_1019_p1;

assign feature_out_d1 = ((and_ln66_1_fu_1006_p2[0:0] == 1'b1) ? v3_reg_1136 : m_5_reg_1129_pp0_iter4_reg);

assign grp_fu_582_p_ce = 1'b1;

assign grp_fu_582_p_din0 = grp_fu_176_p0;

assign grp_fu_582_p_din1 = grp_fu_176_p1;

assign grp_fu_582_p_opcode = 5'd2;

assign grp_fu_586_p_ce = 1'b1;

assign grp_fu_586_p_din0 = grp_fu_182_p0;

assign grp_fu_586_p_din1 = grp_fu_182_p1;

assign grp_fu_586_p_opcode = 5'd2;

assign h_mid27_fu_317_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? 4'd0 : h_fu_102);

assign icmp_ln48_fu_290_p2 = ((indvar_flatten41_fu_114 == 12'd3136) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_311_p2 = ((indvar_flatten_fu_106 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_373_p2 = ((w_fu_98 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln50_mid240_fu_379_p2 = (not_exitcond_flatten_fu_367_p2 & icmp_ln50_fu_373_p2);

assign icmp_ln63_1_fu_694_p2 = ((trunc_ln63_fu_684_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_688_p2 = ((tmp_2_fu_674_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln64_1_fu_775_p2 = ((trunc_ln64_fu_748_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_2_fu_787_p2 = ((tmp_5_fu_755_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln64_3_fu_793_p2 = ((trunc_ln64_1_fu_765_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_769_p2 = ((tmp_4_fu_738_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_881_p2 = ((trunc_ln65_fu_854_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_893_p2 = ((tmp_8_fu_861_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_899_p2 = ((trunc_ln65_1_fu_871_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_875_p2 = ((tmp_7_fu_844_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_970_p2 = ((trunc_ln66_fu_943_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_982_p2 = ((tmp_10_fu_950_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_988_p2 = ((trunc_ln66_1_fu_960_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_964_p2 = ((tmp_s_fu_933_p4 != 8'd255) ? 1'b1 : 1'b0);

assign m_1_fu_712_p3 = ((and_ln63_fu_706_p2[0:0] == 1'b1) ? reg_187 : 32'd4286564766);

assign m_3_fu_817_p3 = ((and_ln64_1_fu_811_p2[0:0] == 1'b1) ? v1_reg_1093 : m_1_reg_1100);

assign m_5_fu_923_p3 = ((and_ln65_1_fu_917_p2[0:0] == 1'b1) ? reg_187 : m_3_reg_1112);

assign not_exitcond_flatten_fu_367_p2 = (icmp_ln49_fu_311_p2 ^ 1'd1);

assign or_ln56_fu_525_p2 = (shl_ln55_1_fu_507_p3 | 5'd1);

assign or_ln63_fu_700_p2 = (icmp_ln63_fu_688_p2 | icmp_ln63_1_fu_694_p2);

assign or_ln64_1_fu_799_p2 = (icmp_ln64_3_fu_793_p2 | icmp_ln64_2_fu_787_p2);

assign or_ln64_fu_781_p2 = (icmp_ln64_fu_769_p2 | icmp_ln64_1_fu_775_p2);

assign or_ln65_1_fu_905_p2 = (icmp_ln65_3_fu_899_p2 | icmp_ln65_2_fu_893_p2);

assign or_ln65_fu_887_p2 = (icmp_ln65_fu_875_p2 | icmp_ln65_1_fu_881_p2);

assign or_ln66_1_fu_994_p2 = (icmp_ln66_3_fu_988_p2 | icmp_ln66_2_fu_982_p2);

assign or_ln66_fu_976_p2 = (icmp_ln66_fu_964_p2 | icmp_ln66_1_fu_970_p2);

assign p_shl1_cast_fu_274_p1 = p_shl1_fu_266_p3;

assign p_shl1_cast_mid1_fu_463_p1 = p_shl1_mid1_fu_455_p3;

assign p_shl1_fu_266_p3 = {{h_fu_102}, {1'd0}};

assign p_shl1_mid1_fu_455_p3 = {{add_ln49_fu_385_p2}, {1'd0}};

assign p_shl2_fu_224_p3 = {{h_fu_102}, {5'd0}};

assign p_shl2_mid1_fu_405_p3 = {{add_ln49_fu_385_p2}, {5'd0}};

assign p_shl3_cast_fu_240_p1 = p_shl3_fu_232_p3;

assign p_shl3_cast_mid1_fu_421_p1 = p_shl3_mid1_fu_413_p3;

assign p_shl3_fu_232_p3 = {{h_fu_102}, {2'd0}};

assign p_shl3_mid1_fu_413_p3 = {{add_ln49_fu_385_p2}, {2'd0}};

assign p_shl_fu_258_p3 = {{h_fu_102}, {4'd0}};

assign p_shl_mid1_fu_447_p3 = {{add_ln49_fu_385_p2}, {4'd0}};

assign select_ln49_1_fu_637_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? 8'd1 : add_ln49_1_fu_631_p2);

assign select_ln49_fu_495_p3 = ((icmp_ln50_mid240_fu_379_p2[0:0] == 1'b1) ? add_ln49_fu_385_p2 : h_mid27_fu_317_p3);

assign shl_ln1_fu_541_p3 = {{add_ln56_fu_535_p2}, {4'd0}};

assign shl_ln2_fu_561_p3 = {{add_ln58_fu_555_p2}, {4'd0}};

assign shl_ln3_fu_823_p3 = {{add_ln67_reg_1088_pp0_iter1_reg}, {4'd0}};

assign shl_ln55_1_fu_507_p3 = {{w_mid2_fu_397_p3}, {1'd0}};

assign shl_ln55_mid1_fu_431_p3 = {{sub_ln55_1_fu_425_p2}, {1'd0}};

assign shl_ln55_mid228_fu_343_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? 10'd0 : shl_ln_fu_250_p3);

assign shl_ln55_mid2_fu_439_p3 = ((icmp_ln50_mid240_fu_379_p2[0:0] == 1'b1) ? shl_ln55_mid1_fu_431_p3 : shl_ln55_mid228_fu_343_p3);

assign shl_ln_fu_250_p3 = {{sub_ln55_fu_244_p2}, {1'd0}};

assign sub_ln55_1_fu_425_p2 = (p_shl2_mid1_fu_405_p3 - p_shl3_cast_mid1_fu_421_p1);

assign sub_ln55_fu_244_p2 = (p_shl2_fu_224_p3 - p_shl3_cast_fu_240_p1);

assign sub_ln67_1_fu_467_p2 = (p_shl_mid1_fu_447_p3 - p_shl1_cast_mid1_fu_463_p1);

assign sub_ln67_fu_278_p2 = (p_shl_fu_258_p3 - p_shl1_cast_fu_274_p1);

assign sub_ln67_mid236_fu_351_p3 = ((icmp_ln49_fu_311_p2[0:0] == 1'b1) ? 8'd0 : sub_ln67_fu_278_p2);

assign sub_ln67_mid2_fu_473_p3 = ((icmp_ln50_mid240_fu_379_p2[0:0] == 1'b1) ? sub_ln67_1_fu_467_p2 : sub_ln67_mid236_fu_351_p3);

assign tmp_10_fu_950_p4 = {{bitcast_ln66_1_fu_947_p1[30:23]}};

assign tmp_2_fu_674_p4 = {{bitcast_ln63_fu_670_p1[30:23]}};

assign tmp_4_fu_738_p4 = {{bitcast_ln64_fu_735_p1[30:23]}};

assign tmp_5_fu_755_p4 = {{bitcast_ln64_1_fu_752_p1[30:23]}};

assign tmp_7_fu_844_p4 = {{bitcast_ln65_fu_840_p1[30:23]}};

assign tmp_8_fu_861_p4 = {{bitcast_ln65_1_fu_858_p1[30:23]}};

assign tmp_fu_569_p4 = {{add_ln55_fu_519_p2[9:1]}};

assign tmp_s_fu_933_p4 = {{bitcast_ln66_fu_930_p1[30:23]}};

assign trunc_ln63_fu_684_p1 = bitcast_ln63_fu_670_p1[22:0];

assign trunc_ln64_1_fu_765_p1 = bitcast_ln64_1_fu_752_p1[22:0];

assign trunc_ln64_fu_748_p1 = bitcast_ln64_fu_735_p1[22:0];

assign trunc_ln65_1_fu_871_p1 = bitcast_ln65_1_fu_858_p1[22:0];

assign trunc_ln65_fu_854_p1 = bitcast_ln65_fu_840_p1[22:0];

assign trunc_ln66_1_fu_960_p1 = bitcast_ln66_1_fu_947_p1[22:0];

assign trunc_ln66_fu_943_p1 = bitcast_ln66_fu_930_p1[22:0];

assign w_mid2_fu_397_p3 = ((empty_45_fu_391_p2[0:0] == 1'b1) ? 4'd0 : w_fu_98);

assign zext_ln55_1_fu_515_p1 = shl_ln55_1_fu_507_p3;

assign zext_ln55_fu_503_p1 = w_mid2_fu_397_p3;

assign zext_ln56_fu_531_p1 = or_ln56_fu_525_p2;

assign zext_ln59_fu_587_p1 = add_ln_fu_579_p3;

assign zext_ln60_fu_598_p1 = add_ln60_fu_592_p2;

assign zext_ln61_fu_730_p1 = add_ln1_fu_724_p3;

assign zext_ln62_fu_836_p1 = add_ln62_reg_1083_pp0_iter2_reg;

assign zext_ln67_fu_1019_p1 = add_ln67_1_reg_1119_pp0_iter4_reg;

endmodule //gtsrb_cnn_maxpool2x2_valid_2
