-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gtsrb_cnn_linear_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem4_AWVALID : OUT STD_LOGIC;
    m_axi_gmem4_AWREADY : IN STD_LOGIC;
    m_axi_gmem4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_WVALID : OUT STD_LOGIC;
    m_axi_gmem4_WREADY : IN STD_LOGIC;
    m_axi_gmem4_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_WLAST : OUT STD_LOGIC;
    m_axi_gmem4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_ARVALID : OUT STD_LOGIC;
    m_axi_gmem4_ARREADY : IN STD_LOGIC;
    m_axi_gmem4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RVALID : IN STD_LOGIC;
    m_axi_gmem4_RREADY : OUT STD_LOGIC;
    m_axi_gmem4_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_RLAST : IN STD_LOGIC;
    m_axi_gmem4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_BVALID : IN STD_LOGIC;
    m_axi_gmem4_BREADY : OUT STD_LOGIC;
    m_axi_gmem4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    W : IN STD_LOGIC_VECTOR (63 downto 0);
    b : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_AWVALID : OUT STD_LOGIC;
    m_axi_gmem5_AWREADY : IN STD_LOGIC;
    m_axi_gmem5_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_WVALID : OUT STD_LOGIC;
    m_axi_gmem5_WREADY : IN STD_LOGIC;
    m_axi_gmem5_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_WLAST : OUT STD_LOGIC;
    m_axi_gmem5_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_ARVALID : OUT STD_LOGIC;
    m_axi_gmem5_ARREADY : IN STD_LOGIC;
    m_axi_gmem5_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RVALID : IN STD_LOGIC;
    m_axi_gmem5_RREADY : OUT STD_LOGIC;
    m_axi_gmem5_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_RLAST : IN STD_LOGIC;
    m_axi_gmem5_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem5_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_BVALID : IN STD_LOGIC;
    m_axi_gmem5_BREADY : OUT STD_LOGIC;
    m_axi_gmem5_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    vout : IN STD_LOGIC_VECTOR (63 downto 0);
    fc1_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    fc1_out_ce0 : OUT STD_LOGIC;
    fc1_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    fc1_out_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    fc1_out_ce1 : OUT STD_LOGIC;
    fc1_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_574_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_ce : OUT STD_LOGIC;
    grp_fu_578_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_ce : OUT STD_LOGIC );
end;


architecture behav of gtsrb_cnn_linear_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gmem5_blk_n_AW : STD_LOGIC;
    signal gmem5_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal trunc_ln83_1_fu_98_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln83_1_reg_130 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln_reg_145 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_idle : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WLAST : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_BREADY : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARVALID : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_RREADY : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0 : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1 : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce : STD_LOGIC;
    signal grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sext_ln83_fu_108_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_150_ce : STD_LOGIC;
    signal grp_fu_154_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gtsrb_cnn_linear_2_Pipeline_VITIS_LOOP_83_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem4_AWVALID : OUT STD_LOGIC;
        m_axi_gmem4_AWREADY : IN STD_LOGIC;
        m_axi_gmem4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_WVALID : OUT STD_LOGIC;
        m_axi_gmem4_WREADY : IN STD_LOGIC;
        m_axi_gmem4_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_WLAST : OUT STD_LOGIC;
        m_axi_gmem4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_ARVALID : OUT STD_LOGIC;
        m_axi_gmem4_ARREADY : IN STD_LOGIC;
        m_axi_gmem4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RVALID : IN STD_LOGIC;
        m_axi_gmem4_RREADY : OUT STD_LOGIC;
        m_axi_gmem4_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_RLAST : IN STD_LOGIC;
        m_axi_gmem4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_BVALID : IN STD_LOGIC;
        m_axi_gmem4_BREADY : OUT STD_LOGIC;
        m_axi_gmem4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_AWVALID : OUT STD_LOGIC;
        m_axi_gmem5_AWREADY : IN STD_LOGIC;
        m_axi_gmem5_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_WVALID : OUT STD_LOGIC;
        m_axi_gmem5_WREADY : IN STD_LOGIC;
        m_axi_gmem5_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_WLAST : OUT STD_LOGIC;
        m_axi_gmem5_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_ARVALID : OUT STD_LOGIC;
        m_axi_gmem5_ARREADY : IN STD_LOGIC;
        m_axi_gmem5_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RVALID : IN STD_LOGIC;
        m_axi_gmem5_RREADY : OUT STD_LOGIC;
        m_axi_gmem5_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_RLAST : IN STD_LOGIC;
        m_axi_gmem5_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem5_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_BVALID : IN STD_LOGIC;
        m_axi_gmem5_BREADY : OUT STD_LOGIC;
        m_axi_gmem5_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln83_1 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln83 : IN STD_LOGIC_VECTOR (61 downto 0);
        W : IN STD_LOGIC_VECTOR (63 downto 0);
        fc1_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        fc1_out_ce0 : OUT STD_LOGIC;
        fc1_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        fc1_out_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        fc1_out_ce1 : OUT STD_LOGIC;
        fc1_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_150_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_150_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_150_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_150_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_150_p_ce : OUT STD_LOGIC;
        grp_fu_154_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_154_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_154_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_154_p_ce : OUT STD_LOGIC );
    end component;


    component gtsrb_cnn_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component gtsrb_cnn_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84 : component gtsrb_cnn_linear_2_Pipeline_VITIS_LOOP_83_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start,
        ap_done => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done,
        ap_idle => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_idle,
        ap_ready => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready,
        m_axi_gmem4_AWVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY => ap_const_logic_0,
        m_axi_gmem4_AWADDR => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY => ap_const_logic_0,
        m_axi_gmem4_WDATA => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WLAST,
        m_axi_gmem4_WID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WID,
        m_axi_gmem4_WUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY => m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID => m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA => m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST => m_axi_gmem4_RLAST,
        m_axi_gmem4_RID => m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM => m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER => m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP => m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID => ap_const_logic_0,
        m_axi_gmem4_BREADY => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP => ap_const_lv2_0,
        m_axi_gmem4_BID => ap_const_lv1_0,
        m_axi_gmem4_BUSER => ap_const_lv1_0,
        m_axi_gmem5_AWVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID,
        m_axi_gmem5_AWREADY => m_axi_gmem5_AWREADY,
        m_axi_gmem5_AWADDR => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR,
        m_axi_gmem5_AWID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID,
        m_axi_gmem5_AWLEN => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN,
        m_axi_gmem5_AWSIZE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE,
        m_axi_gmem5_AWBURST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST,
        m_axi_gmem5_AWLOCK => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK,
        m_axi_gmem5_AWCACHE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE,
        m_axi_gmem5_AWPROT => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT,
        m_axi_gmem5_AWQOS => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS,
        m_axi_gmem5_AWREGION => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION,
        m_axi_gmem5_AWUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER,
        m_axi_gmem5_WVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID,
        m_axi_gmem5_WREADY => m_axi_gmem5_WREADY,
        m_axi_gmem5_WDATA => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA,
        m_axi_gmem5_WSTRB => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB,
        m_axi_gmem5_WLAST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST,
        m_axi_gmem5_WID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID,
        m_axi_gmem5_WUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER,
        m_axi_gmem5_ARVALID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARVALID,
        m_axi_gmem5_ARREADY => ap_const_logic_0,
        m_axi_gmem5_ARADDR => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARADDR,
        m_axi_gmem5_ARID => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARID,
        m_axi_gmem5_ARLEN => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLEN,
        m_axi_gmem5_ARSIZE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARSIZE,
        m_axi_gmem5_ARBURST => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARBURST,
        m_axi_gmem5_ARLOCK => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLOCK,
        m_axi_gmem5_ARCACHE => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARCACHE,
        m_axi_gmem5_ARPROT => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARPROT,
        m_axi_gmem5_ARQOS => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARQOS,
        m_axi_gmem5_ARREGION => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARREGION,
        m_axi_gmem5_ARUSER => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARUSER,
        m_axi_gmem5_RVALID => ap_const_logic_0,
        m_axi_gmem5_RREADY => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_RREADY,
        m_axi_gmem5_RDATA => ap_const_lv32_0,
        m_axi_gmem5_RLAST => ap_const_logic_0,
        m_axi_gmem5_RID => ap_const_lv1_0,
        m_axi_gmem5_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem5_RUSER => ap_const_lv1_0,
        m_axi_gmem5_RRESP => ap_const_lv2_0,
        m_axi_gmem5_BVALID => m_axi_gmem5_BVALID,
        m_axi_gmem5_BREADY => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY,
        m_axi_gmem5_BRESP => m_axi_gmem5_BRESP,
        m_axi_gmem5_BID => m_axi_gmem5_BID,
        m_axi_gmem5_BUSER => m_axi_gmem5_BUSER,
        sext_ln83_1 => trunc_ln83_1_reg_130,
        sext_ln83 => trunc_ln_reg_145,
        W => W,
        fc1_out_address0 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0,
        fc1_out_ce0 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0,
        fc1_out_q0 => fc1_out_q0,
        fc1_out_address1 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1,
        fc1_out_ce1 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1,
        fc1_out_q1 => fc1_out_q1,
        grp_fu_150_p_din0 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0,
        grp_fu_150_p_din1 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1,
        grp_fu_150_p_opcode => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_opcode,
        grp_fu_150_p_dout0 => grp_fu_574_p_dout0,
        grp_fu_150_p_ce => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce,
        grp_fu_154_p_din0 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0,
        grp_fu_154_p_din1 => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1,
        grp_fu_154_p_dout0 => grp_fu_578_p_dout0,
        grp_fu_154_p_ce => grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln83_1_reg_130 <= vout(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln_reg_145 <= b(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem5_AWREADY, m_axi_gmem5_BVALID, ap_CS_fsm_state8, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_gmem5_AWREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (m_axi_gmem5_BVALID = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, m_axi_gmem5_AWREADY)
    begin
        if (((m_axi_gmem5_AWREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done)
    begin
        if ((grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(m_axi_gmem5_BVALID)
    begin
        if ((m_axi_gmem5_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem5_BVALID, ap_CS_fsm_state8)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (m_axi_gmem5_BVALID = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_gmem5_BVALID, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (m_axi_gmem5_BVALID = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fc1_out_address0 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0;
    fc1_out_address1 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1;
    fc1_out_ce0 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0;
    fc1_out_ce1 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1;

    gmem5_blk_n_AW_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem5_AWREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            gmem5_blk_n_AW <= m_axi_gmem5_AWREADY;
        else 
            gmem5_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem5_blk_n_B_assign_proc : process(m_axi_gmem5_BVALID, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            gmem5_blk_n_B <= m_axi_gmem5_BVALID;
        else 
            gmem5_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_150_ce_assign_proc : process(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_150_ce <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce;
        else 
            grp_fu_150_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_154_ce_assign_proc : process(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_154_ce <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce;
        else 
            grp_fu_154_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_574_p_ce <= grp_fu_150_ce;
    grp_fu_574_p_din0 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0;
    grp_fu_574_p_din1 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1;
    grp_fu_574_p_opcode <= ap_const_lv2_0;
    grp_fu_578_p_ce <= grp_fu_154_ce;
    grp_fu_578_p_din0 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0;
    grp_fu_578_p_din1 <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1;
    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg;
    m_axi_gmem4_ARADDR <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR;
    m_axi_gmem4_ARBURST <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST;
    m_axi_gmem4_ARCACHE <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE;
    m_axi_gmem4_ARID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID;
    m_axi_gmem4_ARLEN <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN;
    m_axi_gmem4_ARLOCK <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK;
    m_axi_gmem4_ARPROT <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT;
    m_axi_gmem4_ARQOS <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS;
    m_axi_gmem4_ARREGION <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION;
    m_axi_gmem4_ARSIZE <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE;
    m_axi_gmem4_ARUSER <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER;

    m_axi_gmem4_ARVALID_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem4_ARVALID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID;
        else 
            m_axi_gmem4_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem4_AWADDR <= ap_const_lv64_0;
    m_axi_gmem4_AWBURST <= ap_const_lv2_0;
    m_axi_gmem4_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem4_AWID <= ap_const_lv1_0;
    m_axi_gmem4_AWLEN <= ap_const_lv32_0;
    m_axi_gmem4_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem4_AWPROT <= ap_const_lv3_0;
    m_axi_gmem4_AWQOS <= ap_const_lv4_0;
    m_axi_gmem4_AWREGION <= ap_const_lv4_0;
    m_axi_gmem4_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem4_AWUSER <= ap_const_lv1_0;
    m_axi_gmem4_AWVALID <= ap_const_logic_0;
    m_axi_gmem4_BREADY <= ap_const_logic_0;

    m_axi_gmem4_RREADY_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem4_RREADY <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY;
        else 
            m_axi_gmem4_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem4_WDATA <= ap_const_lv32_0;
    m_axi_gmem4_WID <= ap_const_lv1_0;
    m_axi_gmem4_WLAST <= ap_const_logic_0;
    m_axi_gmem4_WSTRB <= ap_const_lv4_0;
    m_axi_gmem4_WUSER <= ap_const_lv1_0;
    m_axi_gmem4_WVALID <= ap_const_logic_0;
    m_axi_gmem5_ARADDR <= ap_const_lv64_0;
    m_axi_gmem5_ARBURST <= ap_const_lv2_0;
    m_axi_gmem5_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem5_ARID <= ap_const_lv1_0;
    m_axi_gmem5_ARLEN <= ap_const_lv32_0;
    m_axi_gmem5_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem5_ARPROT <= ap_const_lv3_0;
    m_axi_gmem5_ARQOS <= ap_const_lv4_0;
    m_axi_gmem5_ARREGION <= ap_const_lv4_0;
    m_axi_gmem5_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem5_ARUSER <= ap_const_lv1_0;
    m_axi_gmem5_ARVALID <= ap_const_logic_0;

    m_axi_gmem5_AWADDR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem5_AWREADY, ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR, ap_CS_fsm_state3, sext_ln83_fu_108_p1)
    begin
        if ((not(((m_axi_gmem5_AWREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem5_AWADDR <= sext_ln83_fu_108_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWADDR <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR;
        else 
            m_axi_gmem5_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem5_AWBURST_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWBURST <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST;
        else 
            m_axi_gmem5_AWBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem5_AWCACHE_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWCACHE <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE;
        else 
            m_axi_gmem5_AWCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem5_AWID_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID;
        else 
            m_axi_gmem5_AWID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem5_AWLEN_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem5_AWREADY, ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN, ap_CS_fsm_state3)
    begin
        if ((not(((m_axi_gmem5_AWREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem5_AWLEN <= ap_const_lv32_2B;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWLEN <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN;
        else 
            m_axi_gmem5_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem5_AWLOCK_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWLOCK <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK;
        else 
            m_axi_gmem5_AWLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem5_AWPROT_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWPROT <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT;
        else 
            m_axi_gmem5_AWPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem5_AWQOS_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWQOS <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS;
        else 
            m_axi_gmem5_AWQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem5_AWREGION_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWREGION <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION;
        else 
            m_axi_gmem5_AWREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem5_AWSIZE_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWSIZE <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE;
        else 
            m_axi_gmem5_AWSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem5_AWUSER_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWUSER <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER;
        else 
            m_axi_gmem5_AWUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem5_AWVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem5_AWREADY, ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID, ap_CS_fsm_state3)
    begin
        if ((not(((m_axi_gmem5_AWREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem5_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_AWVALID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID;
        else 
            m_axi_gmem5_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem5_BREADY_assign_proc : process(m_axi_gmem5_BVALID, ap_CS_fsm_state8, ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (m_axi_gmem5_BVALID = ap_const_logic_1))) then 
            m_axi_gmem5_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_BREADY <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY;
        else 
            m_axi_gmem5_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem5_RREADY <= ap_const_logic_0;
    m_axi_gmem5_WDATA <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA;
    m_axi_gmem5_WID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID;
    m_axi_gmem5_WLAST <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST;
    m_axi_gmem5_WSTRB <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB;
    m_axi_gmem5_WUSER <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER;

    m_axi_gmem5_WVALID_assign_proc : process(ap_CS_fsm_state2, grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem5_WVALID <= grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID;
        else 
            m_axi_gmem5_WVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln83_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln83_1_fu_98_p4),64));

    trunc_ln83_1_fu_98_p4 <= vout(63 downto 2);
end behav;
