// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gtsrb_cnn_linear_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY,
        m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY,
        m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST,
        m_axi_gmem4_WID,
        m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST,
        m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID,
        m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP,
        m_axi_gmem4_BID,
        m_axi_gmem4_BUSER,
        W,
        b,
        m_axi_gmem5_AWVALID,
        m_axi_gmem5_AWREADY,
        m_axi_gmem5_AWADDR,
        m_axi_gmem5_AWID,
        m_axi_gmem5_AWLEN,
        m_axi_gmem5_AWSIZE,
        m_axi_gmem5_AWBURST,
        m_axi_gmem5_AWLOCK,
        m_axi_gmem5_AWCACHE,
        m_axi_gmem5_AWPROT,
        m_axi_gmem5_AWQOS,
        m_axi_gmem5_AWREGION,
        m_axi_gmem5_AWUSER,
        m_axi_gmem5_WVALID,
        m_axi_gmem5_WREADY,
        m_axi_gmem5_WDATA,
        m_axi_gmem5_WSTRB,
        m_axi_gmem5_WLAST,
        m_axi_gmem5_WID,
        m_axi_gmem5_WUSER,
        m_axi_gmem5_ARVALID,
        m_axi_gmem5_ARREADY,
        m_axi_gmem5_ARADDR,
        m_axi_gmem5_ARID,
        m_axi_gmem5_ARLEN,
        m_axi_gmem5_ARSIZE,
        m_axi_gmem5_ARBURST,
        m_axi_gmem5_ARLOCK,
        m_axi_gmem5_ARCACHE,
        m_axi_gmem5_ARPROT,
        m_axi_gmem5_ARQOS,
        m_axi_gmem5_ARREGION,
        m_axi_gmem5_ARUSER,
        m_axi_gmem5_RVALID,
        m_axi_gmem5_RREADY,
        m_axi_gmem5_RDATA,
        m_axi_gmem5_RLAST,
        m_axi_gmem5_RID,
        m_axi_gmem5_RFIFONUM,
        m_axi_gmem5_RUSER,
        m_axi_gmem5_RRESP,
        m_axi_gmem5_BVALID,
        m_axi_gmem5_BREADY,
        m_axi_gmem5_BRESP,
        m_axi_gmem5_BID,
        m_axi_gmem5_BUSER,
        vout,
        fc1_out_address0,
        fc1_out_ce0,
        fc1_out_q0,
        fc1_out_address1,
        fc1_out_ce1,
        fc1_out_q1,
        grp_fu_574_p_din0,
        grp_fu_574_p_din1,
        grp_fu_574_p_opcode,
        grp_fu_574_p_dout0,
        grp_fu_574_p_ce,
        grp_fu_578_p_din0,
        grp_fu_578_p_din1,
        grp_fu_578_p_dout0,
        grp_fu_578_p_ce
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem4_AWVALID;
input   m_axi_gmem4_AWREADY;
output  [63:0] m_axi_gmem4_AWADDR;
output  [0:0] m_axi_gmem4_AWID;
output  [31:0] m_axi_gmem4_AWLEN;
output  [2:0] m_axi_gmem4_AWSIZE;
output  [1:0] m_axi_gmem4_AWBURST;
output  [1:0] m_axi_gmem4_AWLOCK;
output  [3:0] m_axi_gmem4_AWCACHE;
output  [2:0] m_axi_gmem4_AWPROT;
output  [3:0] m_axi_gmem4_AWQOS;
output  [3:0] m_axi_gmem4_AWREGION;
output  [0:0] m_axi_gmem4_AWUSER;
output   m_axi_gmem4_WVALID;
input   m_axi_gmem4_WREADY;
output  [31:0] m_axi_gmem4_WDATA;
output  [3:0] m_axi_gmem4_WSTRB;
output   m_axi_gmem4_WLAST;
output  [0:0] m_axi_gmem4_WID;
output  [0:0] m_axi_gmem4_WUSER;
output   m_axi_gmem4_ARVALID;
input   m_axi_gmem4_ARREADY;
output  [63:0] m_axi_gmem4_ARADDR;
output  [0:0] m_axi_gmem4_ARID;
output  [31:0] m_axi_gmem4_ARLEN;
output  [2:0] m_axi_gmem4_ARSIZE;
output  [1:0] m_axi_gmem4_ARBURST;
output  [1:0] m_axi_gmem4_ARLOCK;
output  [3:0] m_axi_gmem4_ARCACHE;
output  [2:0] m_axi_gmem4_ARPROT;
output  [3:0] m_axi_gmem4_ARQOS;
output  [3:0] m_axi_gmem4_ARREGION;
output  [0:0] m_axi_gmem4_ARUSER;
input   m_axi_gmem4_RVALID;
output   m_axi_gmem4_RREADY;
input  [31:0] m_axi_gmem4_RDATA;
input   m_axi_gmem4_RLAST;
input  [0:0] m_axi_gmem4_RID;
input  [8:0] m_axi_gmem4_RFIFONUM;
input  [0:0] m_axi_gmem4_RUSER;
input  [1:0] m_axi_gmem4_RRESP;
input   m_axi_gmem4_BVALID;
output   m_axi_gmem4_BREADY;
input  [1:0] m_axi_gmem4_BRESP;
input  [0:0] m_axi_gmem4_BID;
input  [0:0] m_axi_gmem4_BUSER;
input  [63:0] W;
input  [63:0] b;
output   m_axi_gmem5_AWVALID;
input   m_axi_gmem5_AWREADY;
output  [63:0] m_axi_gmem5_AWADDR;
output  [0:0] m_axi_gmem5_AWID;
output  [31:0] m_axi_gmem5_AWLEN;
output  [2:0] m_axi_gmem5_AWSIZE;
output  [1:0] m_axi_gmem5_AWBURST;
output  [1:0] m_axi_gmem5_AWLOCK;
output  [3:0] m_axi_gmem5_AWCACHE;
output  [2:0] m_axi_gmem5_AWPROT;
output  [3:0] m_axi_gmem5_AWQOS;
output  [3:0] m_axi_gmem5_AWREGION;
output  [0:0] m_axi_gmem5_AWUSER;
output   m_axi_gmem5_WVALID;
input   m_axi_gmem5_WREADY;
output  [31:0] m_axi_gmem5_WDATA;
output  [3:0] m_axi_gmem5_WSTRB;
output   m_axi_gmem5_WLAST;
output  [0:0] m_axi_gmem5_WID;
output  [0:0] m_axi_gmem5_WUSER;
output   m_axi_gmem5_ARVALID;
input   m_axi_gmem5_ARREADY;
output  [63:0] m_axi_gmem5_ARADDR;
output  [0:0] m_axi_gmem5_ARID;
output  [31:0] m_axi_gmem5_ARLEN;
output  [2:0] m_axi_gmem5_ARSIZE;
output  [1:0] m_axi_gmem5_ARBURST;
output  [1:0] m_axi_gmem5_ARLOCK;
output  [3:0] m_axi_gmem5_ARCACHE;
output  [2:0] m_axi_gmem5_ARPROT;
output  [3:0] m_axi_gmem5_ARQOS;
output  [3:0] m_axi_gmem5_ARREGION;
output  [0:0] m_axi_gmem5_ARUSER;
input   m_axi_gmem5_RVALID;
output   m_axi_gmem5_RREADY;
input  [31:0] m_axi_gmem5_RDATA;
input   m_axi_gmem5_RLAST;
input  [0:0] m_axi_gmem5_RID;
input  [8:0] m_axi_gmem5_RFIFONUM;
input  [0:0] m_axi_gmem5_RUSER;
input  [1:0] m_axi_gmem5_RRESP;
input   m_axi_gmem5_BVALID;
output   m_axi_gmem5_BREADY;
input  [1:0] m_axi_gmem5_BRESP;
input  [0:0] m_axi_gmem5_BID;
input  [0:0] m_axi_gmem5_BUSER;
input  [63:0] vout;
output  [5:0] fc1_out_address0;
output   fc1_out_ce0;
input  [31:0] fc1_out_q0;
output  [5:0] fc1_out_address1;
output   fc1_out_ce1;
input  [31:0] fc1_out_q1;
output  [31:0] grp_fu_574_p_din0;
output  [31:0] grp_fu_574_p_din1;
output  [1:0] grp_fu_574_p_opcode;
input  [31:0] grp_fu_574_p_dout0;
output   grp_fu_574_p_ce;
output  [31:0] grp_fu_578_p_din0;
output  [31:0] grp_fu_578_p_din1;
input  [31:0] grp_fu_578_p_dout0;
output   grp_fu_578_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem4_ARVALID;
reg m_axi_gmem4_RREADY;
reg m_axi_gmem5_AWVALID;
reg[63:0] m_axi_gmem5_AWADDR;
reg[0:0] m_axi_gmem5_AWID;
reg[31:0] m_axi_gmem5_AWLEN;
reg[2:0] m_axi_gmem5_AWSIZE;
reg[1:0] m_axi_gmem5_AWBURST;
reg[1:0] m_axi_gmem5_AWLOCK;
reg[3:0] m_axi_gmem5_AWCACHE;
reg[2:0] m_axi_gmem5_AWPROT;
reg[3:0] m_axi_gmem5_AWQOS;
reg[3:0] m_axi_gmem5_AWREGION;
reg[0:0] m_axi_gmem5_AWUSER;
reg m_axi_gmem5_WVALID;
reg m_axi_gmem5_BREADY;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem5_blk_n_AW;
reg    gmem5_blk_n_B;
wire    ap_CS_fsm_state8;
wire  signed [61:0] trunc_ln83_1_fu_98_p4;
reg   [61:0] trunc_ln83_1_reg_130;
wire    ap_CS_fsm_state2;
reg   [61:0] trunc_ln_reg_145;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_idle;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWVALID;
wire   [63:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWADDR;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLEN;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWSIZE;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWBURST;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLOCK;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWCACHE;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWPROT;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWQOS;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWREGION;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WVALID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WDATA;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WSTRB;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WLAST;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WID;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID;
wire   [63:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_BREADY;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID;
wire   [63:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARVALID;
wire   [63:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARADDR;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARID;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLEN;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARSIZE;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARBURST;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLOCK;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARCACHE;
wire   [2:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARPROT;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARQOS;
wire   [3:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARREGION;
wire   [0:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARUSER;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_RREADY;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY;
wire   [5:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0;
wire   [5:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1;
wire   [1:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_opcode;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0;
wire   [31:0] grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1;
wire    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce;
reg    grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg;
wire    ap_CS_fsm_state3;
wire  signed [63:0] sext_ln83_fu_108_p1;
reg    grp_fu_150_ce;
reg    grp_fu_154_ce;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg = 1'b0;
end

gtsrb_cnn_linear_2_Pipeline_VITIS_LOOP_83_1 grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start),
    .ap_done(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done),
    .ap_idle(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_idle),
    .ap_ready(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready),
    .m_axi_gmem4_AWVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWVALID),
    .m_axi_gmem4_AWREADY(1'b0),
    .m_axi_gmem4_AWADDR(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWADDR),
    .m_axi_gmem4_AWID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWID),
    .m_axi_gmem4_AWLEN(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLEN),
    .m_axi_gmem4_AWSIZE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWSIZE),
    .m_axi_gmem4_AWBURST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWBURST),
    .m_axi_gmem4_AWLOCK(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWLOCK),
    .m_axi_gmem4_AWCACHE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWCACHE),
    .m_axi_gmem4_AWPROT(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWPROT),
    .m_axi_gmem4_AWQOS(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWQOS),
    .m_axi_gmem4_AWREGION(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWREGION),
    .m_axi_gmem4_AWUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_AWUSER),
    .m_axi_gmem4_WVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WVALID),
    .m_axi_gmem4_WREADY(1'b0),
    .m_axi_gmem4_WDATA(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WDATA),
    .m_axi_gmem4_WSTRB(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WSTRB),
    .m_axi_gmem4_WLAST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WLAST),
    .m_axi_gmem4_WID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WID),
    .m_axi_gmem4_WUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_WUSER),
    .m_axi_gmem4_ARVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID),
    .m_axi_gmem4_ARREADY(m_axi_gmem4_ARREADY),
    .m_axi_gmem4_ARADDR(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR),
    .m_axi_gmem4_ARID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID),
    .m_axi_gmem4_ARLEN(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN),
    .m_axi_gmem4_ARSIZE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE),
    .m_axi_gmem4_ARBURST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST),
    .m_axi_gmem4_ARLOCK(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK),
    .m_axi_gmem4_ARCACHE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE),
    .m_axi_gmem4_ARPROT(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT),
    .m_axi_gmem4_ARQOS(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS),
    .m_axi_gmem4_ARREGION(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION),
    .m_axi_gmem4_ARUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER),
    .m_axi_gmem4_RVALID(m_axi_gmem4_RVALID),
    .m_axi_gmem4_RREADY(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY),
    .m_axi_gmem4_RDATA(m_axi_gmem4_RDATA),
    .m_axi_gmem4_RLAST(m_axi_gmem4_RLAST),
    .m_axi_gmem4_RID(m_axi_gmem4_RID),
    .m_axi_gmem4_RFIFONUM(m_axi_gmem4_RFIFONUM),
    .m_axi_gmem4_RUSER(m_axi_gmem4_RUSER),
    .m_axi_gmem4_RRESP(m_axi_gmem4_RRESP),
    .m_axi_gmem4_BVALID(1'b0),
    .m_axi_gmem4_BREADY(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_BREADY),
    .m_axi_gmem4_BRESP(2'd0),
    .m_axi_gmem4_BID(1'd0),
    .m_axi_gmem4_BUSER(1'd0),
    .m_axi_gmem5_AWVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID),
    .m_axi_gmem5_AWREADY(m_axi_gmem5_AWREADY),
    .m_axi_gmem5_AWADDR(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR),
    .m_axi_gmem5_AWID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID),
    .m_axi_gmem5_AWLEN(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN),
    .m_axi_gmem5_AWSIZE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE),
    .m_axi_gmem5_AWBURST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST),
    .m_axi_gmem5_AWLOCK(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK),
    .m_axi_gmem5_AWCACHE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE),
    .m_axi_gmem5_AWPROT(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT),
    .m_axi_gmem5_AWQOS(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS),
    .m_axi_gmem5_AWREGION(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION),
    .m_axi_gmem5_AWUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER),
    .m_axi_gmem5_WVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID),
    .m_axi_gmem5_WREADY(m_axi_gmem5_WREADY),
    .m_axi_gmem5_WDATA(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA),
    .m_axi_gmem5_WSTRB(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB),
    .m_axi_gmem5_WLAST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST),
    .m_axi_gmem5_WID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID),
    .m_axi_gmem5_WUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER),
    .m_axi_gmem5_ARVALID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARVALID),
    .m_axi_gmem5_ARREADY(1'b0),
    .m_axi_gmem5_ARADDR(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARADDR),
    .m_axi_gmem5_ARID(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARID),
    .m_axi_gmem5_ARLEN(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLEN),
    .m_axi_gmem5_ARSIZE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARSIZE),
    .m_axi_gmem5_ARBURST(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARBURST),
    .m_axi_gmem5_ARLOCK(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARLOCK),
    .m_axi_gmem5_ARCACHE(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARCACHE),
    .m_axi_gmem5_ARPROT(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARPROT),
    .m_axi_gmem5_ARQOS(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARQOS),
    .m_axi_gmem5_ARREGION(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARREGION),
    .m_axi_gmem5_ARUSER(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_ARUSER),
    .m_axi_gmem5_RVALID(1'b0),
    .m_axi_gmem5_RREADY(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_RREADY),
    .m_axi_gmem5_RDATA(32'd0),
    .m_axi_gmem5_RLAST(1'b0),
    .m_axi_gmem5_RID(1'd0),
    .m_axi_gmem5_RFIFONUM(9'd0),
    .m_axi_gmem5_RUSER(1'd0),
    .m_axi_gmem5_RRESP(2'd0),
    .m_axi_gmem5_BVALID(m_axi_gmem5_BVALID),
    .m_axi_gmem5_BREADY(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY),
    .m_axi_gmem5_BRESP(m_axi_gmem5_BRESP),
    .m_axi_gmem5_BID(m_axi_gmem5_BID),
    .m_axi_gmem5_BUSER(m_axi_gmem5_BUSER),
    .sext_ln83_1(trunc_ln83_1_reg_130),
    .sext_ln83(trunc_ln_reg_145),
    .W(W),
    .fc1_out_address0(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0),
    .fc1_out_ce0(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0),
    .fc1_out_q0(fc1_out_q0),
    .fc1_out_address1(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1),
    .fc1_out_ce1(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1),
    .fc1_out_q1(fc1_out_q1),
    .grp_fu_150_p_din0(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0),
    .grp_fu_150_p_din1(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1),
    .grp_fu_150_p_opcode(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_opcode),
    .grp_fu_150_p_dout0(grp_fu_574_p_dout0),
    .grp_fu_150_p_ce(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce),
    .grp_fu_154_p_din0(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0),
    .grp_fu_154_p_din1(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1),
    .grp_fu_154_p_dout0(grp_fu_578_p_dout0),
    .grp_fu_154_p_ce(grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_ready == 1'b1)) begin
            grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln83_1_reg_130 <= {{vout[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln_reg_145 <= {{b[63:2]}};
    end
end

always @ (*) begin
    if (((m_axi_gmem5_AWREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem5_BVALID == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state8) & (m_axi_gmem5_BVALID == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (m_axi_gmem5_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        gmem5_blk_n_AW = m_axi_gmem5_AWREADY;
    end else begin
        gmem5_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem5_blk_n_B = m_axi_gmem5_BVALID;
    end else begin
        gmem5_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_150_ce = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_ce;
    end else begin
        grp_fu_150_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_154_ce = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_ce;
    end else begin
        grp_fu_154_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_ARVALID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARVALID;
    end else begin
        m_axi_gmem4_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_RREADY = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_RREADY;
    end else begin
        m_axi_gmem4_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem5_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem5_AWADDR = sext_ln83_fu_108_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWADDR = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWADDR;
    end else begin
        m_axi_gmem5_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWBURST = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWBURST;
    end else begin
        m_axi_gmem5_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWCACHE = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWCACHE;
    end else begin
        m_axi_gmem5_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWID;
    end else begin
        m_axi_gmem5_AWID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem5_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem5_AWLEN = 32'd43;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWLEN = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLEN;
    end else begin
        m_axi_gmem5_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWLOCK = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWLOCK;
    end else begin
        m_axi_gmem5_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWPROT = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWPROT;
    end else begin
        m_axi_gmem5_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWQOS = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWQOS;
    end else begin
        m_axi_gmem5_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWREGION = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWREGION;
    end else begin
        m_axi_gmem5_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWSIZE = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWSIZE;
    end else begin
        m_axi_gmem5_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWUSER = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWUSER;
    end else begin
        m_axi_gmem5_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem5_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem5_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_AWVALID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_AWVALID;
    end else begin
        m_axi_gmem5_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (m_axi_gmem5_BVALID == 1'b1))) begin
        m_axi_gmem5_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_BREADY = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_BREADY;
    end else begin
        m_axi_gmem5_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_WVALID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WVALID;
    end else begin
        m_axi_gmem5_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem5_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (m_axi_gmem5_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign fc1_out_address0 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address0;

assign fc1_out_address1 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_address1;

assign fc1_out_ce0 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce0;

assign fc1_out_ce1 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_fc1_out_ce1;

assign grp_fu_574_p_ce = grp_fu_150_ce;

assign grp_fu_574_p_din0 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din0;

assign grp_fu_574_p_din1 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_150_p_din1;

assign grp_fu_574_p_opcode = 2'd0;

assign grp_fu_578_p_ce = grp_fu_154_ce;

assign grp_fu_578_p_din0 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din0;

assign grp_fu_578_p_din1 = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_grp_fu_154_p_din1;

assign grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_ap_start_reg;

assign m_axi_gmem4_ARADDR = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARADDR;

assign m_axi_gmem4_ARBURST = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARBURST;

assign m_axi_gmem4_ARCACHE = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARCACHE;

assign m_axi_gmem4_ARID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARID;

assign m_axi_gmem4_ARLEN = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLEN;

assign m_axi_gmem4_ARLOCK = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARLOCK;

assign m_axi_gmem4_ARPROT = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARPROT;

assign m_axi_gmem4_ARQOS = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARQOS;

assign m_axi_gmem4_ARREGION = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARREGION;

assign m_axi_gmem4_ARSIZE = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARSIZE;

assign m_axi_gmem4_ARUSER = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem4_ARUSER;

assign m_axi_gmem4_AWADDR = 64'd0;

assign m_axi_gmem4_AWBURST = 2'd0;

assign m_axi_gmem4_AWCACHE = 4'd0;

assign m_axi_gmem4_AWID = 1'd0;

assign m_axi_gmem4_AWLEN = 32'd0;

assign m_axi_gmem4_AWLOCK = 2'd0;

assign m_axi_gmem4_AWPROT = 3'd0;

assign m_axi_gmem4_AWQOS = 4'd0;

assign m_axi_gmem4_AWREGION = 4'd0;

assign m_axi_gmem4_AWSIZE = 3'd0;

assign m_axi_gmem4_AWUSER = 1'd0;

assign m_axi_gmem4_AWVALID = 1'b0;

assign m_axi_gmem4_BREADY = 1'b0;

assign m_axi_gmem4_WDATA = 32'd0;

assign m_axi_gmem4_WID = 1'd0;

assign m_axi_gmem4_WLAST = 1'b0;

assign m_axi_gmem4_WSTRB = 4'd0;

assign m_axi_gmem4_WUSER = 1'd0;

assign m_axi_gmem4_WVALID = 1'b0;

assign m_axi_gmem5_ARADDR = 64'd0;

assign m_axi_gmem5_ARBURST = 2'd0;

assign m_axi_gmem5_ARCACHE = 4'd0;

assign m_axi_gmem5_ARID = 1'd0;

assign m_axi_gmem5_ARLEN = 32'd0;

assign m_axi_gmem5_ARLOCK = 2'd0;

assign m_axi_gmem5_ARPROT = 3'd0;

assign m_axi_gmem5_ARQOS = 4'd0;

assign m_axi_gmem5_ARREGION = 4'd0;

assign m_axi_gmem5_ARSIZE = 3'd0;

assign m_axi_gmem5_ARUSER = 1'd0;

assign m_axi_gmem5_ARVALID = 1'b0;

assign m_axi_gmem5_RREADY = 1'b0;

assign m_axi_gmem5_WDATA = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WDATA;

assign m_axi_gmem5_WID = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WID;

assign m_axi_gmem5_WLAST = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WLAST;

assign m_axi_gmem5_WSTRB = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WSTRB;

assign m_axi_gmem5_WUSER = grp_linear_2_Pipeline_VITIS_LOOP_83_1_fu_84_m_axi_gmem5_WUSER;

assign sext_ln83_fu_108_p1 = trunc_ln83_1_fu_98_p4;

assign trunc_ln83_1_fu_98_p4 = {{vout[63:2]}};

endmodule //gtsrb_cnn_linear_2
