// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gtsrb_cnn_maxpool2x2_valid (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_in_address0,
        feature_in_ce0,
        feature_in_q0,
        feature_in_address1,
        feature_in_ce1,
        feature_in_q1,
        feature_out_address1,
        feature_out_ce1,
        feature_out_we1,
        feature_out_d1,
        grp_fu_582_p_din0,
        grp_fu_582_p_din1,
        grp_fu_582_p_opcode,
        grp_fu_582_p_dout0,
        grp_fu_582_p_ce,
        grp_fu_586_p_din0,
        grp_fu_586_p_din1,
        grp_fu_586_p_opcode,
        grp_fu_586_p_dout0,
        grp_fu_586_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] feature_in_address0;
output   feature_in_ce0;
input  [31:0] feature_in_q0;
output  [9:0] feature_in_address1;
output   feature_in_ce1;
input  [31:0] feature_in_q1;
output  [7:0] feature_out_address1;
output   feature_out_ce1;
output   feature_out_we1;
output  [31:0] feature_out_d1;
output  [31:0] grp_fu_582_p_din0;
output  [31:0] grp_fu_582_p_din1;
output  [4:0] grp_fu_582_p_opcode;
input  [0:0] grp_fu_582_p_dout0;
output   grp_fu_582_p_ce;
output  [31:0] grp_fu_586_p_din0;
output  [31:0] grp_fu_586_p_din1;
output  [4:0] grp_fu_586_p_opcode;
input  [0:0] grp_fu_586_p_dout0;
output   grp_fu_586_p_ce;

reg ap_idle;
reg[9:0] feature_in_address0;
reg feature_in_ce0;
reg[9:0] feature_in_address1;
reg feature_in_ce1;
reg feature_out_ce1;
reg feature_out_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln48_reg_912;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_183;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln48_fu_238_p2;
reg   [0:0] icmp_ln48_reg_912_pp0_iter1_reg;
reg   [0:0] icmp_ln48_reg_912_pp0_iter2_reg;
wire   [6:0] c_cast2_mid2_v_fu_279_p3;
reg   [6:0] c_cast2_mid2_v_reg_916;
reg   [6:0] c_cast2_mid2_v_reg_916_pp0_iter1_reg;
wire   [0:0] select_ln49_3_fu_339_p3;
reg   [0:0] select_ln49_3_reg_922;
reg   [0:0] select_ln49_3_reg_922_pp0_iter1_reg;
wire   [0:0] trunc_ln54_fu_369_p1;
reg   [0:0] trunc_ln54_reg_927;
reg   [0:0] trunc_ln54_reg_927_pp0_iter1_reg;
wire   [1:0] select_ln49_5_fu_425_p3;
reg   [1:0] select_ln49_5_reg_933;
reg   [1:0] select_ln49_5_reg_933_pp0_iter1_reg;
wire   [9:0] add_ln62_fu_471_p2;
reg   [9:0] add_ln62_reg_948;
reg   [9:0] add_ln62_reg_948_pp0_iter1_reg;
reg   [9:0] add_ln62_reg_948_pp0_iter2_reg;
reg   [31:0] v1_reg_953;
wire   [31:0] m_15_fu_564_p3;
reg   [31:0] m_15_reg_960;
wire   [31:0] m_17_fu_670_p3;
reg   [31:0] m_17_reg_972;
wire   [7:0] add_ln67_fu_684_p2;
reg   [7:0] add_ln67_reg_979;
reg   [7:0] add_ln67_reg_979_pp0_iter2_reg;
reg   [7:0] add_ln67_reg_979_pp0_iter3_reg;
wire   [31:0] m_19_fu_777_p3;
reg   [31:0] m_19_reg_989;
reg   [31:0] m_19_reg_989_pp0_iter3_reg;
reg   [31:0] v3_reg_996;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln59_fu_455_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln60_fu_466_p1;
wire   [63:0] zext_ln61_fu_583_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln62_fu_690_p1;
wire   [63:0] zext_ln67_fu_873_p1;
reg   [1:0] w_fu_94;
wire   [1:0] add_ln50_fu_477_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_w_load;
reg   [1:0] h_fu_98;
wire   [1:0] select_ln49_4_fu_361_p3;
reg   [1:0] ap_sig_allocacmp_h_3;
reg   [3:0] indvar_flatten_fu_102;
wire   [3:0] select_ln49_6_fu_489_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [6:0] c_fu_106;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [8:0] indvar_flatten19_fu_110;
wire   [8:0] add_ln48_fu_244_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten19_load;
reg   [31:0] grp_fu_172_p0;
reg   [31:0] grp_fu_172_p1;
reg   [31:0] grp_fu_178_p0;
reg   [31:0] grp_fu_178_p1;
wire   [0:0] trunc_ln55_fu_220_p1;
wire   [3:0] shl_ln_fu_224_p3;
wire   [0:0] icmp_ln49_fu_259_p2;
wire   [6:0] add_ln48_3_fu_273_p2;
wire   [0:0] not_exitcond_flatten_fu_291_p2;
wire   [0:0] icmp_ln50_fu_303_p2;
wire   [1:0] h_mid27_fu_265_p3;
wire   [0:0] icmp_ln50_mid218_fu_309_p2;
wire   [0:0] or_ln49_fu_321_p2;
wire   [1:0] add_ln49_fu_315_p2;
wire   [0:0] trunc_ln55_1_fu_335_p1;
wire   [0:0] trunc_ln55_mid210_fu_297_p2;
wire   [3:0] shl_ln55_mid1_fu_347_p3;
wire   [1:0] select_ln49_fu_327_p3;
wire   [1:0] shl_ln55_fu_373_p2;
wire   [1:0] or_ln56_fu_379_p2;
wire   [3:0] or_ln57_1_fu_355_p2;
wire   [3:0] or_ln57_fu_232_p2;
wire   [1:0] tmp_4_fu_407_p4;
wire   [1:0] tmp_3_fu_397_p4;
wire   [1:0] empty_47_fu_417_p3;
wire   [9:0] add_ln4_fu_443_p5;
wire   [9:0] shl_ln7_fu_385_p5;
wire   [9:0] c_cast_mid2_fu_287_p1;
wire   [9:0] add_ln60_fu_460_p2;
wire   [9:0] shl_ln8_fu_433_p4;
wire   [3:0] add_ln49_3_fu_483_p2;
wire   [31:0] bitcast_ln63_fu_522_p1;
wire   [7:0] tmp_s_fu_526_p4;
wire   [22:0] trunc_ln63_fu_536_p1;
wire   [0:0] icmp_ln63_3_fu_546_p2;
wire   [0:0] icmp_ln63_fu_540_p2;
wire   [0:0] or_ln63_fu_552_p2;
wire   [0:0] and_ln63_fu_558_p2;
wire   [9:0] add_ln5_fu_576_p4;
wire   [31:0] bitcast_ln64_fu_588_p1;
wire   [31:0] bitcast_ln64_3_fu_605_p1;
wire   [7:0] tmp_24_fu_591_p4;
wire   [22:0] trunc_ln64_fu_601_p1;
wire   [0:0] icmp_ln64_7_fu_628_p2;
wire   [0:0] icmp_ln64_fu_622_p2;
wire   [7:0] tmp_25_fu_608_p4;
wire   [22:0] trunc_ln64_3_fu_618_p1;
wire   [0:0] icmp_ln64_9_fu_646_p2;
wire   [0:0] icmp_ln64_8_fu_640_p2;
wire   [0:0] or_ln64_fu_634_p2;
wire   [0:0] or_ln64_3_fu_652_p2;
wire   [0:0] and_ln64_fu_658_p2;
wire   [0:0] and_ln64_3_fu_664_p2;
wire   [7:0] shl_ln9_fu_676_p4;
wire   [7:0] c_cast2_mid2_fu_573_p1;
wire   [31:0] bitcast_ln65_fu_694_p1;
wire   [31:0] bitcast_ln65_3_fu_712_p1;
wire   [7:0] tmp_27_fu_698_p4;
wire   [22:0] trunc_ln65_fu_708_p1;
wire   [0:0] icmp_ln65_7_fu_735_p2;
wire   [0:0] icmp_ln65_fu_729_p2;
wire   [7:0] tmp_28_fu_715_p4;
wire   [22:0] trunc_ln65_3_fu_725_p1;
wire   [0:0] icmp_ln65_9_fu_753_p2;
wire   [0:0] icmp_ln65_8_fu_747_p2;
wire   [0:0] or_ln65_fu_741_p2;
wire   [0:0] or_ln65_3_fu_759_p2;
wire   [0:0] and_ln65_fu_765_p2;
wire   [0:0] and_ln65_3_fu_771_p2;
wire   [31:0] bitcast_ln66_fu_784_p1;
wire   [31:0] bitcast_ln66_3_fu_801_p1;
wire   [7:0] tmp_30_fu_787_p4;
wire   [22:0] trunc_ln66_fu_797_p1;
wire   [0:0] icmp_ln66_7_fu_824_p2;
wire   [0:0] icmp_ln66_fu_818_p2;
wire   [7:0] tmp_31_fu_804_p4;
wire   [22:0] trunc_ln66_3_fu_814_p1;
wire   [0:0] icmp_ln66_9_fu_842_p2;
wire   [0:0] icmp_ln66_8_fu_836_p2;
wire   [0:0] or_ln66_fu_830_p2;
wire   [0:0] or_ln66_3_fu_848_p2;
wire   [0:0] and_ln66_fu_854_p2;
wire   [0:0] and_ln66_3_fu_860_p2;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

gtsrb_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_106 <= c_cast2_mid2_v_fu_279_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_106 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            h_fu_98 <= select_ln49_4_fu_361_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            h_fu_98 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten19_fu_110 <= add_ln48_fu_244_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_110 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_102 <= select_ln49_6_fu_489_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_102 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            w_fu_94 <= add_ln50_fu_477_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            w_fu_94 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_238_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln62_reg_948 <= add_ln62_fu_471_p2;
        c_cast2_mid2_v_reg_916 <= c_cast2_mid2_v_fu_279_p3;
        select_ln49_3_reg_922 <= select_ln49_3_fu_339_p3;
        select_ln49_5_reg_933[1] <= select_ln49_5_fu_425_p3[1];
        trunc_ln54_reg_927 <= trunc_ln54_fu_369_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln62_reg_948_pp0_iter1_reg <= add_ln62_reg_948;
        add_ln62_reg_948_pp0_iter2_reg <= add_ln62_reg_948_pp0_iter1_reg;
        c_cast2_mid2_v_reg_916_pp0_iter1_reg <= c_cast2_mid2_v_reg_916;
        icmp_ln48_reg_912 <= icmp_ln48_fu_238_p2;
        icmp_ln48_reg_912_pp0_iter1_reg <= icmp_ln48_reg_912;
        icmp_ln48_reg_912_pp0_iter2_reg <= icmp_ln48_reg_912_pp0_iter1_reg;
        m_15_reg_960 <= m_15_fu_564_p3;
        select_ln49_3_reg_922_pp0_iter1_reg <= select_ln49_3_reg_922;
        select_ln49_5_reg_933_pp0_iter1_reg[1] <= select_ln49_5_reg_933[1];
        trunc_ln54_reg_927_pp0_iter1_reg <= trunc_ln54_reg_927;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln67_reg_979 <= add_ln67_fu_684_p2;
        add_ln67_reg_979_pp0_iter2_reg <= add_ln67_reg_979;
        add_ln67_reg_979_pp0_iter3_reg <= add_ln67_reg_979_pp0_iter2_reg;
        m_17_reg_972 <= m_17_fu_670_p3;
        m_19_reg_989 <= m_19_fu_777_p3;
        m_19_reg_989_pp0_iter3_reg <= m_19_reg_989;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln48_reg_912 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_183 <= feature_in_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_reg_912 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        v1_reg_953 <= feature_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v3_reg_996 <= feature_in_q0;
    end
end

always @ (*) begin
    if (((icmp_ln48_reg_912 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln48_reg_912_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_h_3 = 2'd0;
    end else begin
        ap_sig_allocacmp_h_3 = h_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten19_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten19_load = indvar_flatten19_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_w_load = 2'd0;
    end else begin
        ap_sig_allocacmp_w_load = w_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_in_address0 = zext_ln62_fu_690_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_in_address0 = zext_ln60_fu_466_p1;
    end else begin
        feature_in_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feature_in_address1 = zext_ln61_fu_583_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_in_address1 = zext_ln59_fu_455_p1;
    end else begin
        feature_in_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        feature_in_ce0 = 1'b1;
    end else begin
        feature_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        feature_in_ce1 = 1'b1;
    end else begin
        feature_in_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_out_ce1 = 1'b1;
    end else begin
        feature_out_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_out_we1 = 1'b1;
    end else begin
        feature_out_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_172_p0 = v1_reg_953;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_172_p0 = feature_in_q1;
    end else begin
        grp_fu_172_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_172_p1 = m_15_fu_564_p3;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_172_p1 = 32'd4286564766;
    end else begin
        grp_fu_172_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_178_p0 = v3_reg_996;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_178_p0 = feature_in_q1;
    end else begin
        grp_fu_178_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_178_p1 = m_19_reg_989;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_178_p1 = m_17_reg_972;
    end else begin
        grp_fu_178_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln48_3_fu_273_p2 = (ap_sig_allocacmp_c_load + 7'd1);

assign add_ln48_fu_244_p2 = (ap_sig_allocacmp_indvar_flatten19_load + 9'd1);

assign add_ln49_3_fu_483_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln49_fu_315_p2 = (h_mid27_fu_265_p3 + 2'd1);

assign add_ln4_fu_443_p5 = {{{{select_ln49_3_fu_339_p3}, {1'd0}}, {trunc_ln54_fu_369_p1}}, {c_cast2_mid2_v_fu_279_p3}};

assign add_ln50_fu_477_p2 = (select_ln49_fu_327_p3 + 2'd1);

assign add_ln5_fu_576_p4 = {{{select_ln49_5_reg_933_pp0_iter1_reg}, {trunc_ln54_reg_927_pp0_iter1_reg}}, {c_cast2_mid2_v_reg_916_pp0_iter1_reg}};

assign add_ln60_fu_460_p2 = (shl_ln7_fu_385_p5 + c_cast_mid2_fu_287_p1);

assign add_ln62_fu_471_p2 = (shl_ln8_fu_433_p4 + c_cast_mid2_fu_287_p1);

assign add_ln67_fu_684_p2 = (shl_ln9_fu_676_p4 + c_cast2_mid2_fu_573_p1);

assign and_ln63_fu_558_p2 = (or_ln63_fu_552_p2 & grp_fu_582_p_dout0);

assign and_ln64_3_fu_664_p2 = (grp_fu_582_p_dout0 & and_ln64_fu_658_p2);

assign and_ln64_fu_658_p2 = (or_ln64_fu_634_p2 & or_ln64_3_fu_652_p2);

assign and_ln65_3_fu_771_p2 = (grp_fu_586_p_dout0 & and_ln65_fu_765_p2);

assign and_ln65_fu_765_p2 = (or_ln65_fu_741_p2 & or_ln65_3_fu_759_p2);

assign and_ln66_3_fu_860_p2 = (grp_fu_586_p_dout0 & and_ln66_fu_854_p2);

assign and_ln66_fu_854_p2 = (or_ln66_fu_830_p2 & or_ln66_3_fu_848_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bitcast_ln63_fu_522_p1 = reg_183;

assign bitcast_ln64_3_fu_605_p1 = m_15_reg_960;

assign bitcast_ln64_fu_588_p1 = v1_reg_953;

assign bitcast_ln65_3_fu_712_p1 = m_17_reg_972;

assign bitcast_ln65_fu_694_p1 = reg_183;

assign bitcast_ln66_3_fu_801_p1 = m_19_reg_989_pp0_iter3_reg;

assign bitcast_ln66_fu_784_p1 = v3_reg_996;

assign c_cast2_mid2_fu_573_p1 = c_cast2_mid2_v_reg_916_pp0_iter1_reg;

assign c_cast2_mid2_v_fu_279_p3 = ((icmp_ln49_fu_259_p2[0:0] == 1'b1) ? add_ln48_3_fu_273_p2 : ap_sig_allocacmp_c_load);

assign c_cast_mid2_fu_287_p1 = c_cast2_mid2_v_fu_279_p3;

assign empty_47_fu_417_p3 = ((icmp_ln49_fu_259_p2[0:0] == 1'b1) ? 2'd1 : tmp_4_fu_407_p4);

assign feature_out_address1 = zext_ln67_fu_873_p1;

assign feature_out_d1 = ((and_ln66_3_fu_860_p2[0:0] == 1'b1) ? v3_reg_996 : m_19_reg_989_pp0_iter3_reg);

assign grp_fu_582_p_ce = 1'b1;

assign grp_fu_582_p_din0 = grp_fu_172_p0;

assign grp_fu_582_p_din1 = grp_fu_172_p1;

assign grp_fu_582_p_opcode = 5'd2;

assign grp_fu_586_p_ce = 1'b1;

assign grp_fu_586_p_din0 = grp_fu_178_p0;

assign grp_fu_586_p_din1 = grp_fu_178_p1;

assign grp_fu_586_p_opcode = 5'd2;

assign h_mid27_fu_265_p3 = ((icmp_ln49_fu_259_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_h_3);

assign icmp_ln48_fu_238_p2 = ((ap_sig_allocacmp_indvar_flatten19_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_259_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_303_p2 = ((ap_sig_allocacmp_w_load == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln50_mid218_fu_309_p2 = (not_exitcond_flatten_fu_291_p2 & icmp_ln50_fu_303_p2);

assign icmp_ln63_3_fu_546_p2 = ((trunc_ln63_fu_536_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_540_p2 = ((tmp_s_fu_526_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln64_7_fu_628_p2 = ((trunc_ln64_fu_601_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_8_fu_640_p2 = ((tmp_25_fu_608_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln64_9_fu_646_p2 = ((trunc_ln64_3_fu_618_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_622_p2 = ((tmp_24_fu_591_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_7_fu_735_p2 = ((trunc_ln65_fu_708_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_8_fu_747_p2 = ((tmp_28_fu_715_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_9_fu_753_p2 = ((trunc_ln65_3_fu_725_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_729_p2 = ((tmp_27_fu_698_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_824_p2 = ((trunc_ln66_fu_797_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_836_p2 = ((tmp_31_fu_804_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln66_9_fu_842_p2 = ((trunc_ln66_3_fu_814_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_818_p2 = ((tmp_30_fu_787_p4 != 8'd255) ? 1'b1 : 1'b0);

assign m_15_fu_564_p3 = ((and_ln63_fu_558_p2[0:0] == 1'b1) ? reg_183 : 32'd4286564766);

assign m_17_fu_670_p3 = ((and_ln64_3_fu_664_p2[0:0] == 1'b1) ? v1_reg_953 : m_15_reg_960);

assign m_19_fu_777_p3 = ((and_ln65_3_fu_771_p2[0:0] == 1'b1) ? reg_183 : m_17_reg_972);

assign not_exitcond_flatten_fu_291_p2 = (icmp_ln49_fu_259_p2 ^ 1'd1);

assign or_ln49_fu_321_p2 = (icmp_ln50_mid218_fu_309_p2 | icmp_ln49_fu_259_p2);

assign or_ln56_fu_379_p2 = (shl_ln55_fu_373_p2 | 2'd1);

assign or_ln57_1_fu_355_p2 = (shl_ln55_mid1_fu_347_p3 | 4'd4);

assign or_ln57_fu_232_p2 = (shl_ln_fu_224_p3 | 4'd4);

assign or_ln63_fu_552_p2 = (icmp_ln63_fu_540_p2 | icmp_ln63_3_fu_546_p2);

assign or_ln64_3_fu_652_p2 = (icmp_ln64_9_fu_646_p2 | icmp_ln64_8_fu_640_p2);

assign or_ln64_fu_634_p2 = (icmp_ln64_fu_622_p2 | icmp_ln64_7_fu_628_p2);

assign or_ln65_3_fu_759_p2 = (icmp_ln65_9_fu_753_p2 | icmp_ln65_8_fu_747_p2);

assign or_ln65_fu_741_p2 = (icmp_ln65_fu_729_p2 | icmp_ln65_7_fu_735_p2);

assign or_ln66_3_fu_848_p2 = (icmp_ln66_9_fu_842_p2 | icmp_ln66_8_fu_836_p2);

assign or_ln66_fu_830_p2 = (icmp_ln66_fu_818_p2 | icmp_ln66_7_fu_824_p2);

assign select_ln49_3_fu_339_p3 = ((icmp_ln50_mid218_fu_309_p2[0:0] == 1'b1) ? trunc_ln55_1_fu_335_p1 : trunc_ln55_mid210_fu_297_p2);

assign select_ln49_4_fu_361_p3 = ((icmp_ln50_mid218_fu_309_p2[0:0] == 1'b1) ? add_ln49_fu_315_p2 : h_mid27_fu_265_p3);

assign select_ln49_5_fu_425_p3 = ((icmp_ln50_mid218_fu_309_p2[0:0] == 1'b1) ? tmp_3_fu_397_p4 : empty_47_fu_417_p3);

assign select_ln49_6_fu_489_p3 = ((icmp_ln49_fu_259_p2[0:0] == 1'b1) ? 4'd1 : add_ln49_3_fu_483_p2);

assign select_ln49_fu_327_p3 = ((or_ln49_fu_321_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_w_load);

assign shl_ln55_fu_373_p2 = select_ln49_fu_327_p3 << 2'd1;

assign shl_ln55_mid1_fu_347_p3 = {{trunc_ln55_1_fu_335_p1}, {3'd0}};

assign shl_ln7_fu_385_p5 = {{{{select_ln49_3_fu_339_p3}, {1'd0}}, {or_ln56_fu_379_p2}}, {6'd0}};

assign shl_ln8_fu_433_p4 = {{{select_ln49_5_fu_425_p3}, {or_ln56_fu_379_p2}}, {6'd0}};

assign shl_ln9_fu_676_p4 = {{{select_ln49_3_reg_922_pp0_iter1_reg}, {trunc_ln54_reg_927_pp0_iter1_reg}}, {6'd0}};

assign shl_ln_fu_224_p3 = {{trunc_ln55_fu_220_p1}, {3'd0}};

assign tmp_24_fu_591_p4 = {{bitcast_ln64_fu_588_p1[30:23]}};

assign tmp_25_fu_608_p4 = {{bitcast_ln64_3_fu_605_p1[30:23]}};

assign tmp_27_fu_698_p4 = {{bitcast_ln65_fu_694_p1[30:23]}};

assign tmp_28_fu_715_p4 = {{bitcast_ln65_3_fu_712_p1[30:23]}};

assign tmp_30_fu_787_p4 = {{bitcast_ln66_fu_784_p1[30:23]}};

assign tmp_31_fu_804_p4 = {{bitcast_ln66_3_fu_801_p1[30:23]}};

assign tmp_3_fu_397_p4 = {{or_ln57_1_fu_355_p2[3:2]}};

assign tmp_4_fu_407_p4 = {{or_ln57_fu_232_p2[3:2]}};

assign tmp_s_fu_526_p4 = {{bitcast_ln63_fu_522_p1[30:23]}};

assign trunc_ln54_fu_369_p1 = select_ln49_fu_327_p3[0:0];

assign trunc_ln55_1_fu_335_p1 = add_ln49_fu_315_p2[0:0];

assign trunc_ln55_fu_220_p1 = ap_sig_allocacmp_h_3[0:0];

assign trunc_ln55_mid210_fu_297_p2 = (trunc_ln55_fu_220_p1 & not_exitcond_flatten_fu_291_p2);

assign trunc_ln63_fu_536_p1 = bitcast_ln63_fu_522_p1[22:0];

assign trunc_ln64_3_fu_618_p1 = bitcast_ln64_3_fu_605_p1[22:0];

assign trunc_ln64_fu_601_p1 = bitcast_ln64_fu_588_p1[22:0];

assign trunc_ln65_3_fu_725_p1 = bitcast_ln65_3_fu_712_p1[22:0];

assign trunc_ln65_fu_708_p1 = bitcast_ln65_fu_694_p1[22:0];

assign trunc_ln66_3_fu_814_p1 = bitcast_ln66_3_fu_801_p1[22:0];

assign trunc_ln66_fu_797_p1 = bitcast_ln66_fu_784_p1[22:0];

assign zext_ln59_fu_455_p1 = add_ln4_fu_443_p5;

assign zext_ln60_fu_466_p1 = add_ln60_fu_460_p2;

assign zext_ln61_fu_583_p1 = add_ln5_fu_576_p4;

assign zext_ln62_fu_690_p1 = add_ln62_reg_948_pp0_iter2_reg;

assign zext_ln67_fu_873_p1 = add_ln67_reg_979_pp0_iter3_reg;

always @ (posedge ap_clk) begin
    select_ln49_5_reg_933[0] <= 1'b1;
    select_ln49_5_reg_933_pp0_iter1_reg[0] <= 1'b1;
end

endmodule //gtsrb_cnn_maxpool2x2_valid
