// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gtsrb_cnn_linear (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        W,
        b,
        p3_out_address0,
        p3_out_ce0,
        p3_out_q0,
        fc1_out_address1,
        fc1_out_ce1,
        fc1_out_we1,
        fc1_out_d1,
        grp_fu_574_p_din0,
        grp_fu_574_p_din1,
        grp_fu_574_p_opcode,
        grp_fu_574_p_dout0,
        grp_fu_574_p_ce,
        grp_fu_578_p_din0,
        grp_fu_578_p_din1,
        grp_fu_578_p_dout0,
        grp_fu_578_p_ce,
        grp_fu_582_p_din0,
        grp_fu_582_p_din1,
        grp_fu_582_p_opcode,
        grp_fu_582_p_dout0,
        grp_fu_582_p_ce
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [63:0] W;
input  [63:0] b;
output  [7:0] p3_out_address0;
output   p3_out_ce0;
input  [31:0] p3_out_q0;
output  [5:0] fc1_out_address1;
output   fc1_out_ce1;
output   fc1_out_we1;
output  [31:0] fc1_out_d1;
output  [31:0] grp_fu_574_p_din0;
output  [31:0] grp_fu_574_p_din1;
output  [1:0] grp_fu_574_p_opcode;
input  [31:0] grp_fu_574_p_dout0;
output   grp_fu_574_p_ce;
output  [31:0] grp_fu_578_p_din0;
output  [31:0] grp_fu_578_p_din1;
input  [31:0] grp_fu_578_p_dout0;
output   grp_fu_578_p_ce;
output  [31:0] grp_fu_582_p_din0;
output  [31:0] grp_fu_582_p_din1;
output  [4:0] grp_fu_582_p_opcode;
input  [0:0] grp_fu_582_p_dout0;
output   grp_fu_582_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem3_ARVALID;
reg[63:0] m_axi_gmem3_ARADDR;
reg[0:0] m_axi_gmem3_ARID;
reg[31:0] m_axi_gmem3_ARLEN;
reg[2:0] m_axi_gmem3_ARSIZE;
reg[1:0] m_axi_gmem3_ARBURST;
reg[1:0] m_axi_gmem3_ARLOCK;
reg[3:0] m_axi_gmem3_ARCACHE;
reg[2:0] m_axi_gmem3_ARPROT;
reg[3:0] m_axi_gmem3_ARQOS;
reg[3:0] m_axi_gmem3_ARREGION;
reg[0:0] m_axi_gmem3_ARUSER;
reg m_axi_gmem3_RREADY;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem3_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem3_blk_n_R;
wire    ap_CS_fsm_state10;
wire  signed [62:0] sext_ln83_fu_118_p1;
reg  signed [62:0] sext_ln83_reg_186;
wire   [5:0] trunc_ln83_fu_142_p1;
reg   [5:0] trunc_ln83_reg_194;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln83_fu_130_p2;
reg   [63:0] gmem3_addr_reg_200;
reg   [31:0] gmem3_addr_read_reg_206;
wire   [31:0] acc_fu_170_p1;
reg   [31:0] acc_reg_211;
wire    ap_CS_fsm_state11;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_idle;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWVALID;
wire   [63:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWADDR;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWID;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLEN;
wire   [2:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWSIZE;
wire   [1:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWBURST;
wire   [1:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLOCK;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWCACHE;
wire   [2:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWPROT;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWQOS;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWREGION;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWUSER;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WVALID;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WDATA;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WSTRB;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WLAST;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WID;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WUSER;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID;
wire   [63:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN;
wire   [2:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE;
wire   [1:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST;
wire   [1:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE;
wire   [2:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS;
wire   [3:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION;
wire   [0:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_BREADY;
wire   [7:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0;
wire   [5:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1;
wire   [1:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_opcode;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0;
wire   [31:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1;
wire   [4:0] grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode;
wire    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce;
reg    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg;
wire    ap_CS_fsm_state12;
wire  signed [63:0] sext_ln84_fu_155_p1;
reg   [6:0] wbase_fu_66;
wire   [6:0] add_ln83_fu_136_p2;
wire   [61:0] trunc_ln_fu_108_p4;
wire   [62:0] zext_ln83_fu_146_p1;
wire   [62:0] add_ln84_fu_150_p2;
reg    grp_fu_216_ce;
reg    grp_fu_220_ce;
reg    grp_fu_224_ce;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg = 1'b0;
end

gtsrb_cnn_linear_Pipeline_VITIS_LOOP_86_2 grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start),
    .ap_done(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done),
    .ap_idle(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_idle),
    .ap_ready(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready),
    .acc(acc_reg_211),
    .zext_ln83(trunc_ln83_reg_194),
    .trunc_ln87_s(trunc_ln83_reg_194),
    .W(W),
    .m_axi_gmem3_AWVALID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(1'b0),
    .m_axi_gmem3_AWADDR(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(1'b0),
    .m_axi_gmem3_WDATA(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(m_axi_gmem3_ARREADY),
    .m_axi_gmem3_ARADDR(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(m_axi_gmem3_RVALID),
    .m_axi_gmem3_RREADY(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(m_axi_gmem3_RDATA),
    .m_axi_gmem3_RLAST(m_axi_gmem3_RLAST),
    .m_axi_gmem3_RID(m_axi_gmem3_RID),
    .m_axi_gmem3_RFIFONUM(m_axi_gmem3_RFIFONUM),
    .m_axi_gmem3_RUSER(m_axi_gmem3_RUSER),
    .m_axi_gmem3_RRESP(m_axi_gmem3_RRESP),
    .m_axi_gmem3_BVALID(1'b0),
    .m_axi_gmem3_BREADY(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(2'd0),
    .m_axi_gmem3_BID(1'd0),
    .m_axi_gmem3_BUSER(1'd0),
    .p3_out_address0(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0),
    .p3_out_ce0(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0),
    .p3_out_q0(p3_out_q0),
    .fc1_out_address1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1),
    .fc1_out_ce1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1),
    .fc1_out_we1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1),
    .fc1_out_d1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1),
    .grp_fu_216_p_din0(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0),
    .grp_fu_216_p_din1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1),
    .grp_fu_216_p_opcode(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_opcode),
    .grp_fu_216_p_dout0(grp_fu_574_p_dout0),
    .grp_fu_216_p_ce(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce),
    .grp_fu_220_p_din0(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0),
    .grp_fu_220_p_din1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1),
    .grp_fu_220_p_dout0(grp_fu_578_p_dout0),
    .grp_fu_220_p_ce(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce),
    .grp_fu_224_p_din0(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0),
    .grp_fu_224_p_din1(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1),
    .grp_fu_224_p_opcode(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode),
    .grp_fu_224_p_dout0(grp_fu_582_p_dout0),
    .grp_fu_224_p_ce(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready == 1'b1)) begin
            grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        wbase_fu_66 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_130_p2 == 1'd0))) begin
        wbase_fu_66 <= add_ln83_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        acc_reg_211 <= acc_fu_170_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem3_addr_read_reg_206 <= m_axi_gmem3_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_130_p2 == 1'd0))) begin
        gmem3_addr_reg_200 <= sext_ln84_fu_155_p1;
        trunc_ln83_reg_194 <= trunc_ln83_fu_142_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln83_reg_186 <= sext_ln83_fu_118_p1;
    end
end

always @ (*) begin
    if ((m_axi_gmem3_RVALID == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem3_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_130_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_130_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem3_blk_n_AR = m_axi_gmem3_ARREADY;
    end else begin
        gmem3_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem3_blk_n_R = m_axi_gmem3_RVALID;
    end else begin
        gmem3_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_216_ce = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce;
    end else begin
        grp_fu_216_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_220_ce = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce;
    end else begin
        grp_fu_220_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_224_ce = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce;
    end else begin
        grp_fu_224_ce = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmem3_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_ARADDR = gmem3_addr_reg_200;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARADDR = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR;
    end else begin
        m_axi_gmem3_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARBURST = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST;
    end else begin
        m_axi_gmem3_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARCACHE = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE;
    end else begin
        m_axi_gmem3_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARID = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID;
    end else begin
        m_axi_gmem3_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem3_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARLEN = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN;
    end else begin
        m_axi_gmem3_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARLOCK = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK;
    end else begin
        m_axi_gmem3_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARPROT = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT;
    end else begin
        m_axi_gmem3_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARQOS = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS;
    end else begin
        m_axi_gmem3_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARREGION = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION;
    end else begin
        m_axi_gmem3_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARSIZE = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE;
    end else begin
        m_axi_gmem3_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARUSER = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER;
    end else begin
        m_axi_gmem3_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem3_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_ARVALID = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID;
    end else begin
        m_axi_gmem3_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem3_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem3_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem3_RREADY = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY;
    end else begin
        m_axi_gmem3_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_130_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_gmem3_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((m_axi_gmem3_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_170_p1 = gmem3_addr_read_reg_206;

assign add_ln83_fu_136_p2 = (wbase_fu_66 + 7'd1);

assign add_ln84_fu_150_p2 = ($signed(zext_ln83_fu_146_p1) + $signed(sext_ln83_reg_186));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign fc1_out_address1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1;

assign fc1_out_ce1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1;

assign fc1_out_d1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1;

assign fc1_out_we1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1;

assign grp_fu_574_p_ce = grp_fu_216_ce;

assign grp_fu_574_p_din0 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0;

assign grp_fu_574_p_din1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1;

assign grp_fu_574_p_opcode = 2'd0;

assign grp_fu_578_p_ce = grp_fu_220_ce;

assign grp_fu_578_p_din0 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0;

assign grp_fu_578_p_din1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1;

assign grp_fu_582_p_ce = grp_fu_224_ce;

assign grp_fu_582_p_din0 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0;

assign grp_fu_582_p_din1 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1;

assign grp_fu_582_p_opcode = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode;

assign grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg;

assign icmp_ln83_fu_130_p2 = ((wbase_fu_66 == 7'd64) ? 1'b1 : 1'b0);

assign m_axi_gmem3_AWADDR = 64'd0;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = 32'd0;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_AWVALID = 1'b0;

assign m_axi_gmem3_BREADY = 1'b0;

assign m_axi_gmem3_WDATA = 32'd0;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 4'd0;

assign m_axi_gmem3_WUSER = 1'd0;

assign m_axi_gmem3_WVALID = 1'b0;

assign p3_out_address0 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0;

assign p3_out_ce0 = grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0;

assign sext_ln83_fu_118_p1 = $signed(trunc_ln_fu_108_p4);

assign sext_ln84_fu_155_p1 = $signed(add_ln84_fu_150_p2);

assign trunc_ln83_fu_142_p1 = wbase_fu_66[5:0];

assign trunc_ln_fu_108_p4 = {{b[63:2]}};

assign zext_ln83_fu_146_p1 = wbase_fu_66;

endmodule //gtsrb_cnn_linear
