-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gtsrb_cnn_maxpool2x2_valid is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    feature_in_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    feature_in_ce0 : OUT STD_LOGIC;
    feature_in_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_in_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    feature_in_ce1 : OUT STD_LOGIC;
    feature_in_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_out_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_out_ce1 : OUT STD_LOGIC;
    feature_out_we1 : OUT STD_LOGIC;
    feature_out_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_582_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_582_p_ce : OUT STD_LOGIC;
    grp_fu_586_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_586_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_586_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_586_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_586_p_ce : OUT STD_LOGIC );
end;


architecture behav of gtsrb_cnn_maxpool2x2_valid is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_FF7FC99E : STD_LOGIC_VECTOR (31 downto 0) := "11111111011111111100100110011110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln48_reg_912 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal reg_183 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln48_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_912_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_912_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal c_cast2_mid2_v_fu_279_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal c_cast2_mid2_v_reg_916 : STD_LOGIC_VECTOR (6 downto 0);
    signal c_cast2_mid2_v_reg_916_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln49_3_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_3_reg_922 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_3_reg_922_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln54_fu_369_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln54_reg_927 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln54_reg_927_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_5_fu_425_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_5_reg_933 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_5_reg_933_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln62_fu_471_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln62_reg_948 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln62_reg_948_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln62_reg_948_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal v1_reg_953 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_15_fu_564_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_15_reg_960 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_17_fu_670_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_17_reg_972 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_fu_684_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln67_reg_979 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln67_reg_979_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln67_reg_979_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_19_fu_777_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_19_reg_989 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_19_reg_989_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_reg_996 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln59_fu_455_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln60_fu_466_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln61_fu_583_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln62_fu_690_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln67_fu_873_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal w_fu_94 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln50_fu_477_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_load : STD_LOGIC_VECTOR (1 downto 0);
    signal h_fu_98 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_4_fu_361_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_h_3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_102 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln49_6_fu_489_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal c_fu_106 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten19_fu_110 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln48_fu_244_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten19_load : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_172_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_172_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_178_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_178_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln55_fu_220_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_224_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln49_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln48_3_fu_273_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal not_exitcond_flatten_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_mid27_fu_265_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln50_mid218_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_315_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln55_1_fu_335_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_mid210_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln55_mid1_fu_347_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln49_fu_327_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln55_fu_373_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln56_fu_379_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln57_1_fu_355_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln57_fu_232_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_407_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_397_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_47_fu_417_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln4_fu_443_p5 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln7_fu_385_p5 : STD_LOGIC_VECTOR (9 downto 0);
    signal c_cast_mid2_fu_287_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln60_fu_460_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln8_fu_433_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln49_3_fu_483_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal bitcast_ln63_fu_522_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_526_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln63_fu_536_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln63_3_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln63_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln5_fu_576_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal bitcast_ln64_fu_588_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln64_3_fu_605_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_591_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln64_fu_601_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln64_7_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_608_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln64_3_fu_618_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln64_9_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_8_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln64_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln64_3_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_3_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln9_fu_676_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_cast2_mid2_fu_573_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln65_fu_694_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln65_3_fu_712_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_698_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_fu_708_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln65_7_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_715_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_3_fu_725_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln65_9_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_8_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_3_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_3_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln66_fu_784_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln66_3_fu_801_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_30_fu_787_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln66_fu_797_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln66_7_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_804_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln66_3_fu_814_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln66_9_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_8_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_3_fu_848_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_3_fu_860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gtsrb_cnn_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component gtsrb_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gtsrb_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    c_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_106 <= c_cast2_mid2_v_fu_279_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_106 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    h_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    h_fu_98 <= select_ln49_4_fu_361_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    h_fu_98 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten19_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten19_fu_110 <= add_ln48_fu_244_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten19_fu_110 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_102 <= select_ln49_6_fu_489_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_102 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    w_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    w_fu_94 <= add_ln50_fu_477_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_94 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_fu_238_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln62_reg_948 <= add_ln62_fu_471_p2;
                c_cast2_mid2_v_reg_916 <= c_cast2_mid2_v_fu_279_p3;
                select_ln49_3_reg_922 <= select_ln49_3_fu_339_p3;
                    select_ln49_5_reg_933(1) <= select_ln49_5_fu_425_p3(1);
                trunc_ln54_reg_927 <= trunc_ln54_fu_369_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln62_reg_948_pp0_iter1_reg <= add_ln62_reg_948;
                add_ln62_reg_948_pp0_iter2_reg <= add_ln62_reg_948_pp0_iter1_reg;
                c_cast2_mid2_v_reg_916_pp0_iter1_reg <= c_cast2_mid2_v_reg_916;
                icmp_ln48_reg_912 <= icmp_ln48_fu_238_p2;
                icmp_ln48_reg_912_pp0_iter1_reg <= icmp_ln48_reg_912;
                icmp_ln48_reg_912_pp0_iter2_reg <= icmp_ln48_reg_912_pp0_iter1_reg;
                m_15_reg_960 <= m_15_fu_564_p3;
                select_ln49_3_reg_922_pp0_iter1_reg <= select_ln49_3_reg_922;
                    select_ln49_5_reg_933_pp0_iter1_reg(1) <= select_ln49_5_reg_933(1);
                trunc_ln54_reg_927_pp0_iter1_reg <= trunc_ln54_reg_927;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln67_reg_979 <= add_ln67_fu_684_p2;
                add_ln67_reg_979_pp0_iter2_reg <= add_ln67_reg_979;
                add_ln67_reg_979_pp0_iter3_reg <= add_ln67_reg_979_pp0_iter2_reg;
                m_17_reg_972 <= m_17_fu_670_p3;
                m_19_reg_989 <= m_19_fu_777_p3;
                m_19_reg_989_pp0_iter3_reg <= m_19_reg_989;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln48_reg_912 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then
                reg_183 <= feature_in_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_reg_912 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                v1_reg_953 <= feature_in_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                v3_reg_996 <= feature_in_q0;
            end if;
        end if;
    end process;
    select_ln49_5_reg_933(0) <= '1';
    select_ln49_5_reg_933_pp0_iter1_reg(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2, ap_idle_pp0_1to4, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln48_3_fu_273_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv7_1));
    add_ln48_fu_244_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten19_load) + unsigned(ap_const_lv9_1));
    add_ln49_3_fu_483_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln49_fu_315_p2 <= std_logic_vector(unsigned(h_mid27_fu_265_p3) + unsigned(ap_const_lv2_1));
    add_ln4_fu_443_p5 <= (((select_ln49_3_fu_339_p3 & ap_const_lv1_0) & trunc_ln54_fu_369_p1) & c_cast2_mid2_v_fu_279_p3);
    add_ln50_fu_477_p2 <= std_logic_vector(unsigned(select_ln49_fu_327_p3) + unsigned(ap_const_lv2_1));
    add_ln5_fu_576_p4 <= ((select_ln49_5_reg_933_pp0_iter1_reg & trunc_ln54_reg_927_pp0_iter1_reg) & c_cast2_mid2_v_reg_916_pp0_iter1_reg);
    add_ln60_fu_460_p2 <= std_logic_vector(unsigned(shl_ln7_fu_385_p5) + unsigned(c_cast_mid2_fu_287_p1));
    add_ln62_fu_471_p2 <= std_logic_vector(unsigned(shl_ln8_fu_433_p4) + unsigned(c_cast_mid2_fu_287_p1));
    add_ln67_fu_684_p2 <= std_logic_vector(unsigned(shl_ln9_fu_676_p4) + unsigned(c_cast2_mid2_fu_573_p1));
    and_ln63_fu_558_p2 <= (or_ln63_fu_552_p2 and grp_fu_582_p_dout0);
    and_ln64_3_fu_664_p2 <= (grp_fu_582_p_dout0 and and_ln64_fu_658_p2);
    and_ln64_fu_658_p2 <= (or_ln64_fu_634_p2 and or_ln64_3_fu_652_p2);
    and_ln65_3_fu_771_p2 <= (grp_fu_586_p_dout0 and and_ln65_fu_765_p2);
    and_ln65_fu_765_p2 <= (or_ln65_fu_741_p2 and or_ln65_3_fu_759_p2);
    and_ln66_3_fu_860_p2 <= (grp_fu_586_p_dout0 and and_ln66_fu_854_p2);
    and_ln66_fu_854_p2 <= (or_ln66_fu_830_p2 and or_ln66_3_fu_848_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln48_reg_912)
    begin
        if (((icmp_ln48_reg_912 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln48_reg_912_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln48_reg_912_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_h_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, h_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_h_3 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_h_3 <= h_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten19_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten19_fu_110)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten19_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten19_load <= indvar_flatten19_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_w_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, w_fu_94, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_w_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_w_load <= w_fu_94;
        end if; 
    end process;

    bitcast_ln63_fu_522_p1 <= reg_183;
    bitcast_ln64_3_fu_605_p1 <= m_15_reg_960;
    bitcast_ln64_fu_588_p1 <= v1_reg_953;
    bitcast_ln65_3_fu_712_p1 <= m_17_reg_972;
    bitcast_ln65_fu_694_p1 <= reg_183;
    bitcast_ln66_3_fu_801_p1 <= m_19_reg_989_pp0_iter3_reg;
    bitcast_ln66_fu_784_p1 <= v3_reg_996;
    c_cast2_mid2_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_cast2_mid2_v_reg_916_pp0_iter1_reg),8));
    c_cast2_mid2_v_fu_279_p3 <= 
        add_ln48_3_fu_273_p2 when (icmp_ln49_fu_259_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    c_cast_mid2_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_cast2_mid2_v_fu_279_p3),10));
    empty_47_fu_417_p3 <= 
        ap_const_lv2_1 when (icmp_ln49_fu_259_p2(0) = '1') else 
        tmp_4_fu_407_p4;

    feature_in_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln60_fu_466_p1, ap_block_pp0_stage1, zext_ln62_fu_690_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            feature_in_address0 <= zext_ln62_fu_690_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_in_address0 <= zext_ln60_fu_466_p1(10 - 1 downto 0);
        else 
            feature_in_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    feature_in_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, zext_ln59_fu_455_p1, ap_block_pp0_stage0, zext_ln61_fu_583_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            feature_in_address1 <= zext_ln61_fu_583_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_in_address1 <= zext_ln59_fu_455_p1(10 - 1 downto 0);
        else 
            feature_in_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    feature_in_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            feature_in_ce0 <= ap_const_logic_1;
        else 
            feature_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    feature_in_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            feature_in_ce1 <= ap_const_logic_1;
        else 
            feature_in_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    feature_out_address1 <= zext_ln67_fu_873_p1(8 - 1 downto 0);

    feature_out_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_out_ce1 <= ap_const_logic_1;
        else 
            feature_out_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    feature_out_d1 <= 
        v3_reg_996 when (and_ln66_3_fu_860_p2(0) = '1') else 
        m_19_reg_989_pp0_iter3_reg;

    feature_out_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_out_we1 <= ap_const_logic_1;
        else 
            feature_out_we1 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_172_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, feature_in_q1, v1_reg_953, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_172_p0 <= v1_reg_953;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_172_p0 <= feature_in_q1;
        else 
            grp_fu_172_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_172_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_15_fu_564_p3, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_172_p1 <= m_15_fu_564_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_172_p1 <= ap_const_lv32_FF7FC99E;
        else 
            grp_fu_172_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_178_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, feature_in_q1, v3_reg_996, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_178_p0 <= v3_reg_996;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_178_p0 <= feature_in_q1;
        else 
            grp_fu_178_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_178_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, m_17_reg_972, m_19_reg_989, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_178_p1 <= m_19_reg_989;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_178_p1 <= m_17_reg_972;
        else 
            grp_fu_178_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_582_p_ce <= ap_const_logic_1;
    grp_fu_582_p_din0 <= grp_fu_172_p0;
    grp_fu_582_p_din1 <= grp_fu_172_p1;
    grp_fu_582_p_opcode <= ap_const_lv5_2;
    grp_fu_586_p_ce <= ap_const_logic_1;
    grp_fu_586_p_din0 <= grp_fu_178_p0;
    grp_fu_586_p_din1 <= grp_fu_178_p1;
    grp_fu_586_p_opcode <= ap_const_lv5_2;
    h_mid27_fu_265_p3 <= 
        ap_const_lv2_0 when (icmp_ln49_fu_259_p2(0) = '1') else 
        ap_sig_allocacmp_h_3;
    icmp_ln48_fu_238_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten19_load = ap_const_lv9_100) else "0";
    icmp_ln49_fu_259_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_4) else "0";
    icmp_ln50_fu_303_p2 <= "1" when (ap_sig_allocacmp_w_load = ap_const_lv2_2) else "0";
    icmp_ln50_mid218_fu_309_p2 <= (not_exitcond_flatten_fu_291_p2 and icmp_ln50_fu_303_p2);
    icmp_ln63_3_fu_546_p2 <= "1" when (trunc_ln63_fu_536_p1 = ap_const_lv23_0) else "0";
    icmp_ln63_fu_540_p2 <= "0" when (tmp_s_fu_526_p4 = ap_const_lv8_FF) else "1";
    icmp_ln64_7_fu_628_p2 <= "1" when (trunc_ln64_fu_601_p1 = ap_const_lv23_0) else "0";
    icmp_ln64_8_fu_640_p2 <= "0" when (tmp_25_fu_608_p4 = ap_const_lv8_FF) else "1";
    icmp_ln64_9_fu_646_p2 <= "1" when (trunc_ln64_3_fu_618_p1 = ap_const_lv23_0) else "0";
    icmp_ln64_fu_622_p2 <= "0" when (tmp_24_fu_591_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_7_fu_735_p2 <= "1" when (trunc_ln65_fu_708_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_8_fu_747_p2 <= "0" when (tmp_28_fu_715_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_9_fu_753_p2 <= "1" when (trunc_ln65_3_fu_725_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_fu_729_p2 <= "0" when (tmp_27_fu_698_p4 = ap_const_lv8_FF) else "1";
    icmp_ln66_7_fu_824_p2 <= "1" when (trunc_ln66_fu_797_p1 = ap_const_lv23_0) else "0";
    icmp_ln66_8_fu_836_p2 <= "0" when (tmp_31_fu_804_p4 = ap_const_lv8_FF) else "1";
    icmp_ln66_9_fu_842_p2 <= "1" when (trunc_ln66_3_fu_814_p1 = ap_const_lv23_0) else "0";
    icmp_ln66_fu_818_p2 <= "0" when (tmp_30_fu_787_p4 = ap_const_lv8_FF) else "1";
    m_15_fu_564_p3 <= 
        reg_183 when (and_ln63_fu_558_p2(0) = '1') else 
        ap_const_lv32_FF7FC99E;
    m_17_fu_670_p3 <= 
        v1_reg_953 when (and_ln64_3_fu_664_p2(0) = '1') else 
        m_15_reg_960;
    m_19_fu_777_p3 <= 
        reg_183 when (and_ln65_3_fu_771_p2(0) = '1') else 
        m_17_reg_972;
    not_exitcond_flatten_fu_291_p2 <= (icmp_ln49_fu_259_p2 xor ap_const_lv1_1);
    or_ln49_fu_321_p2 <= (icmp_ln50_mid218_fu_309_p2 or icmp_ln49_fu_259_p2);
    or_ln56_fu_379_p2 <= (shl_ln55_fu_373_p2 or ap_const_lv2_1);
    or_ln57_1_fu_355_p2 <= (shl_ln55_mid1_fu_347_p3 or ap_const_lv4_4);
    or_ln57_fu_232_p2 <= (shl_ln_fu_224_p3 or ap_const_lv4_4);
    or_ln63_fu_552_p2 <= (icmp_ln63_fu_540_p2 or icmp_ln63_3_fu_546_p2);
    or_ln64_3_fu_652_p2 <= (icmp_ln64_9_fu_646_p2 or icmp_ln64_8_fu_640_p2);
    or_ln64_fu_634_p2 <= (icmp_ln64_fu_622_p2 or icmp_ln64_7_fu_628_p2);
    or_ln65_3_fu_759_p2 <= (icmp_ln65_9_fu_753_p2 or icmp_ln65_8_fu_747_p2);
    or_ln65_fu_741_p2 <= (icmp_ln65_fu_729_p2 or icmp_ln65_7_fu_735_p2);
    or_ln66_3_fu_848_p2 <= (icmp_ln66_9_fu_842_p2 or icmp_ln66_8_fu_836_p2);
    or_ln66_fu_830_p2 <= (icmp_ln66_fu_818_p2 or icmp_ln66_7_fu_824_p2);
    select_ln49_3_fu_339_p3 <= 
        trunc_ln55_1_fu_335_p1 when (icmp_ln50_mid218_fu_309_p2(0) = '1') else 
        trunc_ln55_mid210_fu_297_p2;
    select_ln49_4_fu_361_p3 <= 
        add_ln49_fu_315_p2 when (icmp_ln50_mid218_fu_309_p2(0) = '1') else 
        h_mid27_fu_265_p3;
    select_ln49_5_fu_425_p3 <= 
        tmp_3_fu_397_p4 when (icmp_ln50_mid218_fu_309_p2(0) = '1') else 
        empty_47_fu_417_p3;
    select_ln49_6_fu_489_p3 <= 
        ap_const_lv4_1 when (icmp_ln49_fu_259_p2(0) = '1') else 
        add_ln49_3_fu_483_p2;
    select_ln49_fu_327_p3 <= 
        ap_const_lv2_0 when (or_ln49_fu_321_p2(0) = '1') else 
        ap_sig_allocacmp_w_load;
    shl_ln55_fu_373_p2 <= std_logic_vector(shift_left(unsigned(select_ln49_fu_327_p3),to_integer(unsigned('0' & ap_const_lv2_1(2-1 downto 0)))));
    shl_ln55_mid1_fu_347_p3 <= (trunc_ln55_1_fu_335_p1 & ap_const_lv3_0);
    shl_ln7_fu_385_p5 <= (((select_ln49_3_fu_339_p3 & ap_const_lv1_0) & or_ln56_fu_379_p2) & ap_const_lv6_0);
    shl_ln8_fu_433_p4 <= ((select_ln49_5_fu_425_p3 & or_ln56_fu_379_p2) & ap_const_lv6_0);
    shl_ln9_fu_676_p4 <= ((select_ln49_3_reg_922_pp0_iter1_reg & trunc_ln54_reg_927_pp0_iter1_reg) & ap_const_lv6_0);
    shl_ln_fu_224_p3 <= (trunc_ln55_fu_220_p1 & ap_const_lv3_0);
    tmp_24_fu_591_p4 <= bitcast_ln64_fu_588_p1(30 downto 23);
    tmp_25_fu_608_p4 <= bitcast_ln64_3_fu_605_p1(30 downto 23);
    tmp_27_fu_698_p4 <= bitcast_ln65_fu_694_p1(30 downto 23);
    tmp_28_fu_715_p4 <= bitcast_ln65_3_fu_712_p1(30 downto 23);
    tmp_30_fu_787_p4 <= bitcast_ln66_fu_784_p1(30 downto 23);
    tmp_31_fu_804_p4 <= bitcast_ln66_3_fu_801_p1(30 downto 23);
    tmp_3_fu_397_p4 <= or_ln57_1_fu_355_p2(3 downto 2);
    tmp_4_fu_407_p4 <= or_ln57_fu_232_p2(3 downto 2);
    tmp_s_fu_526_p4 <= bitcast_ln63_fu_522_p1(30 downto 23);
    trunc_ln54_fu_369_p1 <= select_ln49_fu_327_p3(1 - 1 downto 0);
    trunc_ln55_1_fu_335_p1 <= add_ln49_fu_315_p2(1 - 1 downto 0);
    trunc_ln55_fu_220_p1 <= ap_sig_allocacmp_h_3(1 - 1 downto 0);
    trunc_ln55_mid210_fu_297_p2 <= (trunc_ln55_fu_220_p1 and not_exitcond_flatten_fu_291_p2);
    trunc_ln63_fu_536_p1 <= bitcast_ln63_fu_522_p1(23 - 1 downto 0);
    trunc_ln64_3_fu_618_p1 <= bitcast_ln64_3_fu_605_p1(23 - 1 downto 0);
    trunc_ln64_fu_601_p1 <= bitcast_ln64_fu_588_p1(23 - 1 downto 0);
    trunc_ln65_3_fu_725_p1 <= bitcast_ln65_3_fu_712_p1(23 - 1 downto 0);
    trunc_ln65_fu_708_p1 <= bitcast_ln65_fu_694_p1(23 - 1 downto 0);
    trunc_ln66_3_fu_814_p1 <= bitcast_ln66_3_fu_801_p1(23 - 1 downto 0);
    trunc_ln66_fu_797_p1 <= bitcast_ln66_fu_784_p1(23 - 1 downto 0);
    zext_ln59_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln4_fu_443_p5),64));
    zext_ln60_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_fu_460_p2),64));
    zext_ln61_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln5_fu_576_p4),64));
    zext_ln62_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln62_reg_948_pp0_iter2_reg),64));
    zext_ln67_fu_873_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln67_reg_979_pp0_iter3_reg),64));
end behav;
