-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gtsrb_cnn_linear is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem3_AWVALID : OUT STD_LOGIC;
    m_axi_gmem3_AWREADY : IN STD_LOGIC;
    m_axi_gmem3_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_WVALID : OUT STD_LOGIC;
    m_axi_gmem3_WREADY : IN STD_LOGIC;
    m_axi_gmem3_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_WLAST : OUT STD_LOGIC;
    m_axi_gmem3_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_ARVALID : OUT STD_LOGIC;
    m_axi_gmem3_ARREADY : IN STD_LOGIC;
    m_axi_gmem3_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RVALID : IN STD_LOGIC;
    m_axi_gmem3_RREADY : OUT STD_LOGIC;
    m_axi_gmem3_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_RLAST : IN STD_LOGIC;
    m_axi_gmem3_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem3_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_BVALID : IN STD_LOGIC;
    m_axi_gmem3_BREADY : OUT STD_LOGIC;
    m_axi_gmem3_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    W : IN STD_LOGIC_VECTOR (63 downto 0);
    b : IN STD_LOGIC_VECTOR (63 downto 0);
    p3_out_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p3_out_ce0 : OUT STD_LOGIC;
    p3_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    fc1_out_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    fc1_out_ce1 : OUT STD_LOGIC;
    fc1_out_we1 : OUT STD_LOGIC;
    fc1_out_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_574_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_574_p_ce : OUT STD_LOGIC;
    grp_fu_578_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_ce : OUT STD_LOGIC;
    grp_fu_582_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_582_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_582_p_ce : OUT STD_LOGIC );
end;


architecture behav of gtsrb_cnn_linear is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gmem3_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal gmem3_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal sext_ln83_fu_118_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln83_reg_186 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln83_fu_142_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln83_reg_194 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln83_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem3_addr_reg_200 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem3_addr_read_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_fu_170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_reg_211 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_idle : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWVALID : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WVALID : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WLAST : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_BREADY : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0 : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1 : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1 : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce : STD_LOGIC;
    signal grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal sext_ln84_fu_155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal wbase_fu_66 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln83_fu_136_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_fu_108_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln83_fu_146_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln84_fu_150_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_216_ce : STD_LOGIC;
    signal grp_fu_220_ce : STD_LOGIC;
    signal grp_fu_224_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gtsrb_cnn_linear_Pipeline_VITIS_LOOP_86_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln83 : IN STD_LOGIC_VECTOR (5 downto 0);
        trunc_ln87_s : IN STD_LOGIC_VECTOR (5 downto 0);
        W : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem3_AWVALID : OUT STD_LOGIC;
        m_axi_gmem3_AWREADY : IN STD_LOGIC;
        m_axi_gmem3_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem3_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem3_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem3_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem3_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_WVALID : OUT STD_LOGIC;
        m_axi_gmem3_WREADY : IN STD_LOGIC;
        m_axi_gmem3_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem3_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_WLAST : OUT STD_LOGIC;
        m_axi_gmem3_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_ARVALID : OUT STD_LOGIC;
        m_axi_gmem3_ARREADY : IN STD_LOGIC;
        m_axi_gmem3_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem3_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem3_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem3_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem3_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem3_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_RVALID : IN STD_LOGIC;
        m_axi_gmem3_RREADY : OUT STD_LOGIC;
        m_axi_gmem3_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem3_RLAST : IN STD_LOGIC;
        m_axi_gmem3_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem3_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_BVALID : IN STD_LOGIC;
        m_axi_gmem3_BREADY : OUT STD_LOGIC;
        m_axi_gmem3_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem3_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem3_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        p3_out_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p3_out_ce0 : OUT STD_LOGIC;
        p3_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        fc1_out_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        fc1_out_ce1 : OUT STD_LOGIC;
        fc1_out_we1 : OUT STD_LOGIC;
        fc1_out_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_216_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_216_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_216_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_216_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_216_p_ce : OUT STD_LOGIC;
        grp_fu_220_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_ce : OUT STD_LOGIC;
        grp_fu_224_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
        grp_fu_224_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_224_p_ce : OUT STD_LOGIC );
    end component;


    component gtsrb_cnn_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component gtsrb_cnn_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component gtsrb_cnn_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94 : component gtsrb_cnn_linear_Pipeline_VITIS_LOOP_86_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start,
        ap_done => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done,
        ap_idle => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_idle,
        ap_ready => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready,
        acc => acc_reg_211,
        zext_ln83 => trunc_ln83_reg_194,
        trunc_ln87_s => trunc_ln83_reg_194,
        W => W,
        m_axi_gmem3_AWVALID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY => ap_const_logic_0,
        m_axi_gmem3_AWADDR => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY => ap_const_logic_0,
        m_axi_gmem3_WDATA => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WLAST,
        m_axi_gmem3_WID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WID,
        m_axi_gmem3_WUSER => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY => m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID => m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA => m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST => m_axi_gmem3_RLAST,
        m_axi_gmem3_RID => m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM => m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER => m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP => m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID => ap_const_logic_0,
        m_axi_gmem3_BREADY => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP => ap_const_lv2_0,
        m_axi_gmem3_BID => ap_const_lv1_0,
        m_axi_gmem3_BUSER => ap_const_lv1_0,
        p3_out_address0 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0,
        p3_out_ce0 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0,
        p3_out_q0 => p3_out_q0,
        fc1_out_address1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1,
        fc1_out_ce1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1,
        fc1_out_we1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1,
        fc1_out_d1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1,
        grp_fu_216_p_din0 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0,
        grp_fu_216_p_din1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1,
        grp_fu_216_p_opcode => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_opcode,
        grp_fu_216_p_dout0 => grp_fu_574_p_dout0,
        grp_fu_216_p_ce => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce,
        grp_fu_220_p_din0 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0,
        grp_fu_220_p_din1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1,
        grp_fu_220_p_dout0 => grp_fu_578_p_dout0,
        grp_fu_220_p_ce => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce,
        grp_fu_224_p_din0 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0,
        grp_fu_224_p_din1 => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1,
        grp_fu_224_p_opcode => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode,
        grp_fu_224_p_dout0 => grp_fu_582_p_dout0,
        grp_fu_224_p_ce => grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    wbase_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                wbase_fu_66 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln83_fu_130_p2 = ap_const_lv1_0))) then 
                wbase_fu_66 <= add_ln83_fu_136_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                acc_reg_211 <= acc_fu_170_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                gmem3_addr_read_reg_206 <= m_axi_gmem3_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln83_fu_130_p2 = ap_const_lv1_0))) then
                gmem3_addr_reg_200 <= sext_ln84_fu_155_p1;
                trunc_ln83_reg_194 <= trunc_ln83_fu_142_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sext_ln83_reg_186 <= sext_ln83_fu_118_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem3_ARREADY, m_axi_gmem3_RVALID, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state2, icmp_ln83_fu_130_p2, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln83_fu_130_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((m_axi_gmem3_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((m_axi_gmem3_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    acc_fu_170_p1 <= gmem3_addr_read_reg_206;
    add_ln83_fu_136_p2 <= std_logic_vector(unsigned(wbase_fu_66) + unsigned(ap_const_lv7_1));
    add_ln84_fu_150_p2 <= std_logic_vector(unsigned(zext_ln83_fu_146_p1) + unsigned(sext_ln83_reg_186));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state10_blk_assign_proc : process(m_axi_gmem3_RVALID)
    begin
        if ((m_axi_gmem3_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done)
    begin
        if ((grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(m_axi_gmem3_ARREADY)
    begin
        if ((m_axi_gmem3_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln83_fu_130_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln83_fu_130_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln83_fu_130_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln83_fu_130_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fc1_out_address1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_address1;
    fc1_out_ce1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_ce1;
    fc1_out_d1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_d1;
    fc1_out_we1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_fc1_out_we1;

    gmem3_blk_n_AR_assign_proc : process(m_axi_gmem3_ARREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            gmem3_blk_n_AR <= m_axi_gmem3_ARREADY;
        else 
            gmem3_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_R_assign_proc : process(m_axi_gmem3_RVALID, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            gmem3_blk_n_R <= m_axi_gmem3_RVALID;
        else 
            gmem3_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_216_ce_assign_proc : process(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_216_ce <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_ce;
        else 
            grp_fu_216_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_220_ce_assign_proc : process(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_220_ce <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_ce;
        else 
            grp_fu_220_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_224_ce_assign_proc : process(grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_224_ce <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_ce;
        else 
            grp_fu_224_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_574_p_ce <= grp_fu_216_ce;
    grp_fu_574_p_din0 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din0;
    grp_fu_574_p_din1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_216_p_din1;
    grp_fu_574_p_opcode <= ap_const_lv2_0;
    grp_fu_578_p_ce <= grp_fu_220_ce;
    grp_fu_578_p_din0 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din0;
    grp_fu_578_p_din1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_220_p_din1;
    grp_fu_582_p_ce <= grp_fu_224_ce;
    grp_fu_582_p_din0 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din0;
    grp_fu_582_p_din1 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_din1;
    grp_fu_582_p_opcode <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_grp_fu_224_p_opcode;
    grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_ap_start_reg;
    icmp_ln83_fu_130_p2 <= "1" when (wbase_fu_66 = ap_const_lv7_40) else "0";

    m_axi_gmem3_ARADDR_assign_proc : process(m_axi_gmem3_ARREADY, ap_CS_fsm_state3, gmem3_addr_reg_200, ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR, ap_CS_fsm_state12)
    begin
        if (((m_axi_gmem3_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem3_ARADDR <= gmem3_addr_reg_200;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARADDR <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARADDR;
        else 
            m_axi_gmem3_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem3_ARBURST_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARBURST <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARBURST;
        else 
            m_axi_gmem3_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem3_ARCACHE_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARCACHE <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARCACHE;
        else 
            m_axi_gmem3_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem3_ARID_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARID <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARID;
        else 
            m_axi_gmem3_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem3_ARLEN_assign_proc : process(m_axi_gmem3_ARREADY, ap_CS_fsm_state3, ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN, ap_CS_fsm_state12)
    begin
        if (((m_axi_gmem3_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem3_ARLEN <= ap_const_lv32_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARLEN <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLEN;
        else 
            m_axi_gmem3_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem3_ARLOCK_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARLOCK <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARLOCK;
        else 
            m_axi_gmem3_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem3_ARPROT_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARPROT <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARPROT;
        else 
            m_axi_gmem3_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem3_ARQOS_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARQOS <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARQOS;
        else 
            m_axi_gmem3_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem3_ARREGION_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARREGION <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARREGION;
        else 
            m_axi_gmem3_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem3_ARSIZE_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARSIZE <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARSIZE;
        else 
            m_axi_gmem3_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem3_ARUSER_assign_proc : process(ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARUSER <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARUSER;
        else 
            m_axi_gmem3_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem3_ARVALID_assign_proc : process(m_axi_gmem3_ARREADY, ap_CS_fsm_state3, ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID, ap_CS_fsm_state12)
    begin
        if (((m_axi_gmem3_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem3_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_ARVALID <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_ARVALID;
        else 
            m_axi_gmem3_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem3_AWADDR <= ap_const_lv64_0;
    m_axi_gmem3_AWBURST <= ap_const_lv2_0;
    m_axi_gmem3_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem3_AWID <= ap_const_lv1_0;
    m_axi_gmem3_AWLEN <= ap_const_lv32_0;
    m_axi_gmem3_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem3_AWPROT <= ap_const_lv3_0;
    m_axi_gmem3_AWQOS <= ap_const_lv4_0;
    m_axi_gmem3_AWREGION <= ap_const_lv4_0;
    m_axi_gmem3_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem3_AWUSER <= ap_const_lv1_0;
    m_axi_gmem3_AWVALID <= ap_const_logic_0;
    m_axi_gmem3_BREADY <= ap_const_logic_0;

    m_axi_gmem3_RREADY_assign_proc : process(m_axi_gmem3_RVALID, ap_CS_fsm_state10, ap_CS_fsm_state11, grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY, ap_CS_fsm_state12)
    begin
        if (((m_axi_gmem3_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem3_RREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem3_RREADY <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_m_axi_gmem3_RREADY;
        else 
            m_axi_gmem3_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem3_WDATA <= ap_const_lv32_0;
    m_axi_gmem3_WID <= ap_const_lv1_0;
    m_axi_gmem3_WLAST <= ap_const_logic_0;
    m_axi_gmem3_WSTRB <= ap_const_lv4_0;
    m_axi_gmem3_WUSER <= ap_const_lv1_0;
    m_axi_gmem3_WVALID <= ap_const_logic_0;
    p3_out_address0 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_address0;
    p3_out_ce0 <= grp_linear_Pipeline_VITIS_LOOP_86_2_fu_94_p3_out_ce0;
        sext_ln83_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_108_p4),63));

        sext_ln84_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln84_fu_150_p2),64));

    trunc_ln83_fu_142_p1 <= wbase_fu_66(6 - 1 downto 0);
    trunc_ln_fu_108_p4 <= b(63 downto 2);
    zext_ln83_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(wbase_fu_66),63));
end behav;
