-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gtsrb_cnn_maxpool2x2_valid_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    feature_in_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    feature_in_ce0 : OUT STD_LOGIC;
    feature_in_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_in_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    feature_in_ce1 : OUT STD_LOGIC;
    feature_in_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_out_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    feature_out_ce1 : OUT STD_LOGIC;
    feature_out_we1 : OUT STD_LOGIC;
    feature_out_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_582_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_582_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_582_p_ce : OUT STD_LOGIC;
    grp_fu_586_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_586_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_586_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_586_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_586_p_ce : OUT STD_LOGIC );
end;


architecture behav of gtsrb_cnn_maxpool2x2_valid_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_FF7FC99E : STD_LOGIC_VECTOR (31 downto 0) := "11111111011111111100100110011110";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv11_480 : STD_LOGIC_VECTOR (10 downto 0) := "10010000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln48_reg_1060 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal reg_189 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln48_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_1060_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_1060_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal c_cast5_mid2_v_fu_333_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_cast5_mid2_v_reg_1064 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_cast5_mid2_v_reg_1064_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_reg_1080 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_reg_1080_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln62_fu_615_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln62_reg_1085 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln62_reg_1085_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln62_reg_1085_pp0_iter2_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln67_fu_621_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln67_reg_1090 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln67_reg_1090_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal v1_reg_1095 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_8_fu_714_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_8_reg_1102 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_10_fu_819_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_10_reg_1114 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_2_fu_832_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln67_2_reg_1121 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln67_2_reg_1121_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln67_2_reg_1121_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal m_12_fu_925_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_12_reg_1131 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_12_reg_1131_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_reg_1138 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln59_fu_589_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln60_fu_600_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln61_fu_732_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln62_fu_838_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln67_fu_1021_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal w_fu_100 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln50_fu_627_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_load : STD_LOGIC_VECTOR (2 downto 0);
    signal h_fu_104 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln49_fu_497_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_h_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_108 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln49_2_fu_639_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (5 downto 0);
    signal c_fu_112 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten41_fu_116 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln48_fu_298_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten41_load : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_178_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_178_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_184_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_184_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl3_fu_234_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_fu_226_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl3_cast_fu_242_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln55_fu_246_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl1_fu_268_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_fu_260_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_cast_fu_276_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_252_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln49_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln48_2_fu_327_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln67_fu_280_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln57_fu_286_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln50_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_mid27_fu_319_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln50_mid240_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_46_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_387_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_shl3_mid1_fu_415_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_mid1_fu_407_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl3_cast_mid1_fu_423_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln55_2_fu_427_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln55_mid1_fu_433_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln55_mid228_fu_345_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl1_mid1_fu_457_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_mid1_fu_449_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_cast_mid1_fu_465_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln67_2_fu_469_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln67_mid236_fu_353_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln57_3_fu_483_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln57_mid238_fu_361_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_mid2_fu_399_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln55_2_fu_509_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln55_2_fu_517_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln55_mid2_fu_441_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln56_fu_527_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_fu_533_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln56_fu_537_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln57_mid2_fu_489_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln58_fu_557_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln55_fu_521_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_571_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln_fu_581_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln4_fu_543_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal c_cast_mid2_fu_341_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln60_fu_594_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln57_2_fu_551_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln5_fu_563_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln55_fu_505_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln67_mid2_fu_475_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln49_2_fu_633_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal bitcast_ln63_fu_672_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_676_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln63_fu_686_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln63_2_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln63_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln2_fu_726_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal bitcast_ln64_fu_737_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln64_2_fu_754_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_740_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln64_fu_750_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln64_4_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_757_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln64_2_fu_767_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln64_6_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_5_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln64_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln64_2_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_2_fu_813_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln6_fu_825_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal c_cast5_mid2_fu_723_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln65_fu_842_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln65_2_fu_860_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_846_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_fu_856_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln65_4_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_877_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_863_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_2_fu_873_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln65_6_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_5_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_2_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_2_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln66_fu_932_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln66_2_fu_949_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_935_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln66_fu_945_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln66_4_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_952_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln66_2_fu_962_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln66_6_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_5_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_2_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_fu_1002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_2_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gtsrb_cnn_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component gtsrb_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gtsrb_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    c_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_112 <= c_cast5_mid2_v_fu_333_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_112 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    h_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    h_fu_104 <= select_ln49_fu_497_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    h_fu_104 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten41_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten41_fu_116 <= add_ln48_fu_298_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten41_fu_116 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_108 <= select_ln49_2_fu_639_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_108 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    w_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    w_fu_100 <= add_ln50_fu_627_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_100 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_fu_292_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln62_reg_1085 <= add_ln62_fu_615_p2;
                add_ln67_reg_1090 <= add_ln67_fu_621_p2;
                c_cast5_mid2_v_reg_1064 <= c_cast5_mid2_v_fu_333_p3;
                tmp_s_reg_1080 <= add_ln57_2_fu_551_p2(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln62_reg_1085_pp0_iter1_reg <= add_ln62_reg_1085;
                add_ln62_reg_1085_pp0_iter2_reg <= add_ln62_reg_1085_pp0_iter1_reg;
                add_ln67_reg_1090_pp0_iter1_reg <= add_ln67_reg_1090;
                c_cast5_mid2_v_reg_1064_pp0_iter1_reg <= c_cast5_mid2_v_reg_1064;
                icmp_ln48_reg_1060 <= icmp_ln48_fu_292_p2;
                icmp_ln48_reg_1060_pp0_iter1_reg <= icmp_ln48_reg_1060;
                icmp_ln48_reg_1060_pp0_iter2_reg <= icmp_ln48_reg_1060_pp0_iter1_reg;
                m_8_reg_1102 <= m_8_fu_714_p3;
                tmp_s_reg_1080_pp0_iter1_reg <= tmp_s_reg_1080;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln67_2_reg_1121 <= add_ln67_2_fu_832_p2;
                add_ln67_2_reg_1121_pp0_iter2_reg <= add_ln67_2_reg_1121;
                add_ln67_2_reg_1121_pp0_iter3_reg <= add_ln67_2_reg_1121_pp0_iter2_reg;
                m_10_reg_1114 <= m_10_fu_819_p3;
                m_12_reg_1131 <= m_12_fu_925_p3;
                m_12_reg_1131_pp0_iter3_reg <= m_12_reg_1131;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln48_reg_1060 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then
                reg_189 <= feature_in_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_reg_1060 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                v1_reg_1095 <= feature_in_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                v3_reg_1138 <= feature_in_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2, ap_idle_pp0_1to4, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln2_fu_726_p3 <= (tmp_s_reg_1080_pp0_iter1_reg & c_cast5_mid2_v_reg_1064_pp0_iter1_reg);
    add_ln48_2_fu_327_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv6_1));
    add_ln48_fu_298_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten41_load) + unsigned(ap_const_lv11_1));
    add_ln49_2_fu_633_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv6_1));
    add_ln49_fu_387_p2 <= std_logic_vector(unsigned(h_mid27_fu_319_p3) + unsigned(ap_const_lv3_1));
    add_ln50_fu_627_p2 <= std_logic_vector(unsigned(w_mid2_fu_399_p3) + unsigned(ap_const_lv3_1));
    add_ln55_fu_521_p2 <= std_logic_vector(unsigned(zext_ln55_2_fu_517_p1) + unsigned(shl_ln55_mid2_fu_441_p3));
    add_ln56_fu_537_p2 <= std_logic_vector(unsigned(zext_ln56_fu_533_p1) + unsigned(shl_ln55_mid2_fu_441_p3));
    add_ln57_2_fu_551_p2 <= std_logic_vector(unsigned(zext_ln55_2_fu_517_p1) + unsigned(add_ln57_mid2_fu_489_p3));
    add_ln57_3_fu_483_p2 <= std_logic_vector(unsigned(shl_ln55_mid1_fu_433_p3) + unsigned(ap_const_lv8_C));
    add_ln57_fu_286_p2 <= std_logic_vector(unsigned(shl_ln_fu_252_p3) + unsigned(ap_const_lv8_C));
    add_ln57_mid238_fu_361_p3 <= 
        ap_const_lv8_C when (icmp_ln49_fu_313_p2(0) = '1') else 
        add_ln57_fu_286_p2;
    add_ln57_mid2_fu_489_p3 <= 
        add_ln57_3_fu_483_p2 when (icmp_ln50_mid240_fu_381_p2(0) = '1') else 
        add_ln57_mid238_fu_361_p3;
    add_ln58_fu_557_p2 <= std_logic_vector(unsigned(zext_ln56_fu_533_p1) + unsigned(add_ln57_mid2_fu_489_p3));
    add_ln60_fu_594_p2 <= std_logic_vector(unsigned(shl_ln4_fu_543_p3) + unsigned(c_cast_mid2_fu_341_p1));
    add_ln62_fu_615_p2 <= std_logic_vector(unsigned(shl_ln5_fu_563_p3) + unsigned(c_cast_mid2_fu_341_p1));
    add_ln67_2_fu_832_p2 <= std_logic_vector(unsigned(shl_ln6_fu_825_p3) + unsigned(c_cast5_mid2_fu_723_p1));
    add_ln67_fu_621_p2 <= std_logic_vector(unsigned(zext_ln55_fu_505_p1) + unsigned(sub_ln67_mid2_fu_475_p3));
    add_ln_fu_581_p3 <= (tmp_fu_571_p4 & c_cast5_mid2_v_fu_333_p3);
    and_ln63_fu_708_p2 <= (or_ln63_fu_702_p2 and grp_fu_582_p_dout0);
    and_ln64_2_fu_813_p2 <= (grp_fu_582_p_dout0 and and_ln64_fu_807_p2);
    and_ln64_fu_807_p2 <= (or_ln64_fu_783_p2 and or_ln64_2_fu_801_p2);
    and_ln65_2_fu_919_p2 <= (grp_fu_586_p_dout0 and and_ln65_fu_913_p2);
    and_ln65_fu_913_p2 <= (or_ln65_fu_889_p2 and or_ln65_2_fu_907_p2);
    and_ln66_2_fu_1008_p2 <= (grp_fu_586_p_dout0 and and_ln66_fu_1002_p2);
    and_ln66_fu_1002_p2 <= (or_ln66_fu_978_p2 and or_ln66_2_fu_996_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln48_reg_1060)
    begin
        if (((icmp_ln48_reg_1060 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln48_reg_1060_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln48_reg_1060_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_112)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_112;
        end if; 
    end process;


    ap_sig_allocacmp_h_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, h_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_h_2 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_h_2 <= h_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten41_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten41_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten41_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten41_load <= indvar_flatten41_fu_116;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_108)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_w_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, w_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_w_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_w_load <= w_fu_100;
        end if; 
    end process;

    bitcast_ln63_fu_672_p1 <= reg_189;
    bitcast_ln64_2_fu_754_p1 <= m_8_reg_1102;
    bitcast_ln64_fu_737_p1 <= v1_reg_1095;
    bitcast_ln65_2_fu_860_p1 <= m_10_reg_1114;
    bitcast_ln65_fu_842_p1 <= reg_189;
    bitcast_ln66_2_fu_949_p1 <= m_12_reg_1131_pp0_iter3_reg;
    bitcast_ln66_fu_932_p1 <= v3_reg_1138;
    c_cast5_mid2_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_cast5_mid2_v_reg_1064_pp0_iter1_reg),11));
    c_cast5_mid2_v_fu_333_p3 <= 
        add_ln48_2_fu_327_p2 when (icmp_ln49_fu_313_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    c_cast_mid2_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_cast5_mid2_v_fu_333_p3),13));
    empty_46_fu_393_p2 <= (icmp_ln50_mid240_fu_381_p2 or icmp_ln49_fu_313_p2);

    feature_in_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln60_fu_600_p1, ap_block_pp0_stage1, zext_ln62_fu_838_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            feature_in_address0 <= zext_ln62_fu_838_p1(13 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_in_address0 <= zext_ln60_fu_600_p1(13 - 1 downto 0);
        else 
            feature_in_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    feature_in_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, zext_ln59_fu_589_p1, ap_block_pp0_stage0, zext_ln61_fu_732_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            feature_in_address1 <= zext_ln61_fu_732_p1(13 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_in_address1 <= zext_ln59_fu_589_p1(13 - 1 downto 0);
        else 
            feature_in_address1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    feature_in_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            feature_in_ce0 <= ap_const_logic_1;
        else 
            feature_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    feature_in_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            feature_in_ce1 <= ap_const_logic_1;
        else 
            feature_in_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    feature_out_address1 <= zext_ln67_fu_1021_p1(11 - 1 downto 0);

    feature_out_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_out_ce1 <= ap_const_logic_1;
        else 
            feature_out_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    feature_out_d1 <= 
        v3_reg_1138 when (and_ln66_2_fu_1008_p2(0) = '1') else 
        m_12_reg_1131_pp0_iter3_reg;

    feature_out_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            feature_out_we1 <= ap_const_logic_1;
        else 
            feature_out_we1 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_178_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, feature_in_q1, v1_reg_1095, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_178_p0 <= v1_reg_1095;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_178_p0 <= feature_in_q1;
        else 
            grp_fu_178_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_178_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_8_fu_714_p3, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_178_p1 <= m_8_fu_714_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_178_p1 <= ap_const_lv32_FF7FC99E;
        else 
            grp_fu_178_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_184_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, feature_in_q1, v3_reg_1138, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_184_p0 <= v3_reg_1138;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_184_p0 <= feature_in_q1;
        else 
            grp_fu_184_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_184_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, m_10_reg_1114, m_12_reg_1131, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_184_p1 <= m_12_reg_1131;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_184_p1 <= m_10_reg_1114;
        else 
            grp_fu_184_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_582_p_ce <= ap_const_logic_1;
    grp_fu_582_p_din0 <= grp_fu_178_p0;
    grp_fu_582_p_din1 <= grp_fu_178_p1;
    grp_fu_582_p_opcode <= ap_const_lv5_2;
    grp_fu_586_p_ce <= ap_const_logic_1;
    grp_fu_586_p_din0 <= grp_fu_184_p0;
    grp_fu_586_p_din1 <= grp_fu_184_p1;
    grp_fu_586_p_opcode <= ap_const_lv5_2;
    h_mid27_fu_319_p3 <= 
        ap_const_lv3_0 when (icmp_ln49_fu_313_p2(0) = '1') else 
        ap_sig_allocacmp_h_2;
    icmp_ln48_fu_292_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten41_load = ap_const_lv11_480) else "0";
    icmp_ln49_fu_313_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv6_24) else "0";
    icmp_ln50_fu_375_p2 <= "1" when (ap_sig_allocacmp_w_load = ap_const_lv3_6) else "0";
    icmp_ln50_mid240_fu_381_p2 <= (not_exitcond_flatten_fu_369_p2 and icmp_ln50_fu_375_p2);
    icmp_ln63_2_fu_696_p2 <= "1" when (trunc_ln63_fu_686_p1 = ap_const_lv23_0) else "0";
    icmp_ln63_fu_690_p2 <= "0" when (tmp_12_fu_676_p4 = ap_const_lv8_FF) else "1";
    icmp_ln64_4_fu_777_p2 <= "1" when (trunc_ln64_fu_750_p1 = ap_const_lv23_0) else "0";
    icmp_ln64_5_fu_789_p2 <= "0" when (tmp_15_fu_757_p4 = ap_const_lv8_FF) else "1";
    icmp_ln64_6_fu_795_p2 <= "1" when (trunc_ln64_2_fu_767_p1 = ap_const_lv23_0) else "0";
    icmp_ln64_fu_771_p2 <= "0" when (tmp_14_fu_740_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_4_fu_883_p2 <= "1" when (trunc_ln65_fu_856_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_5_fu_895_p2 <= "0" when (tmp_18_fu_863_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_6_fu_901_p2 <= "1" when (trunc_ln65_2_fu_873_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_fu_877_p2 <= "0" when (tmp_17_fu_846_p4 = ap_const_lv8_FF) else "1";
    icmp_ln66_4_fu_972_p2 <= "1" when (trunc_ln66_fu_945_p1 = ap_const_lv23_0) else "0";
    icmp_ln66_5_fu_984_p2 <= "0" when (tmp_21_fu_952_p4 = ap_const_lv8_FF) else "1";
    icmp_ln66_6_fu_990_p2 <= "1" when (trunc_ln66_2_fu_962_p1 = ap_const_lv23_0) else "0";
    icmp_ln66_fu_966_p2 <= "0" when (tmp_20_fu_935_p4 = ap_const_lv8_FF) else "1";
    m_10_fu_819_p3 <= 
        v1_reg_1095 when (and_ln64_2_fu_813_p2(0) = '1') else 
        m_8_reg_1102;
    m_12_fu_925_p3 <= 
        reg_189 when (and_ln65_2_fu_919_p2(0) = '1') else 
        m_10_reg_1114;
    m_8_fu_714_p3 <= 
        reg_189 when (and_ln63_fu_708_p2(0) = '1') else 
        ap_const_lv32_FF7FC99E;
    not_exitcond_flatten_fu_369_p2 <= (icmp_ln49_fu_313_p2 xor ap_const_lv1_1);
    or_ln56_fu_527_p2 <= (shl_ln55_2_fu_509_p3 or ap_const_lv4_1);
    or_ln63_fu_702_p2 <= (icmp_ln63_fu_690_p2 or icmp_ln63_2_fu_696_p2);
    or_ln64_2_fu_801_p2 <= (icmp_ln64_6_fu_795_p2 or icmp_ln64_5_fu_789_p2);
    or_ln64_fu_783_p2 <= (icmp_ln64_fu_771_p2 or icmp_ln64_4_fu_777_p2);
    or_ln65_2_fu_907_p2 <= (icmp_ln65_6_fu_901_p2 or icmp_ln65_5_fu_895_p2);
    or_ln65_fu_889_p2 <= (icmp_ln65_fu_877_p2 or icmp_ln65_4_fu_883_p2);
    or_ln66_2_fu_996_p2 <= (icmp_ln66_6_fu_990_p2 or icmp_ln66_5_fu_984_p2);
    or_ln66_fu_978_p2 <= (icmp_ln66_fu_966_p2 or icmp_ln66_4_fu_972_p2);
    p_shl1_cast_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_268_p3),6));
    p_shl1_cast_mid1_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_mid1_fu_457_p3),6));
    p_shl1_fu_268_p3 <= (ap_sig_allocacmp_h_2 & ap_const_lv1_0);
    p_shl1_mid1_fu_457_p3 <= (add_ln49_fu_387_p2 & ap_const_lv1_0);
    p_shl2_fu_226_p3 <= (ap_sig_allocacmp_h_2 & ap_const_lv4_0);
    p_shl2_mid1_fu_407_p3 <= (add_ln49_fu_387_p2 & ap_const_lv4_0);
    p_shl3_cast_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_fu_234_p3),7));
    p_shl3_cast_mid1_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_mid1_fu_415_p3),7));
    p_shl3_fu_234_p3 <= (ap_sig_allocacmp_h_2 & ap_const_lv2_0);
    p_shl3_mid1_fu_415_p3 <= (add_ln49_fu_387_p2 & ap_const_lv2_0);
    p_shl_fu_260_p3 <= (ap_sig_allocacmp_h_2 & ap_const_lv3_0);
    p_shl_mid1_fu_449_p3 <= (add_ln49_fu_387_p2 & ap_const_lv3_0);
    select_ln49_2_fu_639_p3 <= 
        ap_const_lv6_1 when (icmp_ln49_fu_313_p2(0) = '1') else 
        add_ln49_2_fu_633_p2;
    select_ln49_fu_497_p3 <= 
        add_ln49_fu_387_p2 when (icmp_ln50_mid240_fu_381_p2(0) = '1') else 
        h_mid27_fu_319_p3;
    shl_ln4_fu_543_p3 <= (add_ln56_fu_537_p2 & ap_const_lv5_0);
    shl_ln55_2_fu_509_p3 <= (w_mid2_fu_399_p3 & ap_const_lv1_0);
    shl_ln55_mid1_fu_433_p3 <= (sub_ln55_2_fu_427_p2 & ap_const_lv1_0);
    shl_ln55_mid228_fu_345_p3 <= 
        ap_const_lv8_0 when (icmp_ln49_fu_313_p2(0) = '1') else 
        shl_ln_fu_252_p3;
    shl_ln55_mid2_fu_441_p3 <= 
        shl_ln55_mid1_fu_433_p3 when (icmp_ln50_mid240_fu_381_p2(0) = '1') else 
        shl_ln55_mid228_fu_345_p3;
    shl_ln5_fu_563_p3 <= (add_ln58_fu_557_p2 & ap_const_lv5_0);
    shl_ln6_fu_825_p3 <= (add_ln67_reg_1090_pp0_iter1_reg & ap_const_lv5_0);
    shl_ln_fu_252_p3 <= (sub_ln55_fu_246_p2 & ap_const_lv1_0);
    sub_ln55_2_fu_427_p2 <= std_logic_vector(unsigned(p_shl2_mid1_fu_407_p3) - unsigned(p_shl3_cast_mid1_fu_423_p1));
    sub_ln55_fu_246_p2 <= std_logic_vector(unsigned(p_shl2_fu_226_p3) - unsigned(p_shl3_cast_fu_242_p1));
    sub_ln67_2_fu_469_p2 <= std_logic_vector(unsigned(p_shl_mid1_fu_449_p3) - unsigned(p_shl1_cast_mid1_fu_465_p1));
    sub_ln67_fu_280_p2 <= std_logic_vector(unsigned(p_shl_fu_260_p3) - unsigned(p_shl1_cast_fu_276_p1));
    sub_ln67_mid236_fu_353_p3 <= 
        ap_const_lv6_0 when (icmp_ln49_fu_313_p2(0) = '1') else 
        sub_ln67_fu_280_p2;
    sub_ln67_mid2_fu_475_p3 <= 
        sub_ln67_2_fu_469_p2 when (icmp_ln50_mid240_fu_381_p2(0) = '1') else 
        sub_ln67_mid236_fu_353_p3;
    tmp_12_fu_676_p4 <= bitcast_ln63_fu_672_p1(30 downto 23);
    tmp_14_fu_740_p4 <= bitcast_ln64_fu_737_p1(30 downto 23);
    tmp_15_fu_757_p4 <= bitcast_ln64_2_fu_754_p1(30 downto 23);
    tmp_17_fu_846_p4 <= bitcast_ln65_fu_842_p1(30 downto 23);
    tmp_18_fu_863_p4 <= bitcast_ln65_2_fu_860_p1(30 downto 23);
    tmp_20_fu_935_p4 <= bitcast_ln66_fu_932_p1(30 downto 23);
    tmp_21_fu_952_p4 <= bitcast_ln66_2_fu_949_p1(30 downto 23);
    tmp_fu_571_p4 <= add_ln55_fu_521_p2(7 downto 1);
    trunc_ln63_fu_686_p1 <= bitcast_ln63_fu_672_p1(23 - 1 downto 0);
    trunc_ln64_2_fu_767_p1 <= bitcast_ln64_2_fu_754_p1(23 - 1 downto 0);
    trunc_ln64_fu_750_p1 <= bitcast_ln64_fu_737_p1(23 - 1 downto 0);
    trunc_ln65_2_fu_873_p1 <= bitcast_ln65_2_fu_860_p1(23 - 1 downto 0);
    trunc_ln65_fu_856_p1 <= bitcast_ln65_fu_842_p1(23 - 1 downto 0);
    trunc_ln66_2_fu_962_p1 <= bitcast_ln66_2_fu_949_p1(23 - 1 downto 0);
    trunc_ln66_fu_945_p1 <= bitcast_ln66_fu_932_p1(23 - 1 downto 0);
    w_mid2_fu_399_p3 <= 
        ap_const_lv3_0 when (empty_46_fu_393_p2(0) = '1') else 
        ap_sig_allocacmp_w_load;
    zext_ln55_2_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln55_2_fu_509_p3),8));
    zext_ln55_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w_mid2_fu_399_p3),6));
    zext_ln56_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln56_fu_527_p2),8));
    zext_ln59_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_581_p3),64));
    zext_ln60_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_fu_594_p2),64));
    zext_ln61_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln2_fu_726_p3),64));
    zext_ln62_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln62_reg_1085_pp0_iter2_reg),64));
    zext_ln67_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln67_2_reg_1121_pp0_iter3_reg),64));
end behav;
